### ISSUE TITLE
Does not work on Android 5.0.1 on Nexus 4

### ISSUE THREAD

**Issue by msveshnikov** [delight-im/Android-AdvancedWebView#1]
File picker is shown one time, but after file select no file name in Web form. Next clicks to select button  have no effect

**Comment by mwaclawek** [comment]
Has this been solved? Did you have to change anything?

**Comment by msveshnikov** [comment]
Yes, that was my fault, sorry!
Working great now.
Thank you for saving my time!

Max.
10 янв. 2015 г. 5:52 пользователь "Marco" <notifications@github.com>
написал:

**Comment by mwaclawek** [comment]
No problem, thanks a lot :)
