### ISSUE TITLE
how to access content type and http status code after page finished 

### ISSUE THREAD

**Issue by santoshgistto** [delight-im/Android-AdvancedWebView#101]
how to access content type and http status code after page finished ?

**Comment by ocram** [comment]
There's no way to retrieve the HTTP response headers, unfortunately.

Android's built-in components don't provide any way to do this and they don't allow for a more efficient solution than fetching the page along with the headers yourself, either.

So what you could do is intercept all page requests in `shouldOverrideUrlLoading`, issue a request to the specified URL yourself with a HTTP client, save the HTTP response headers, and then let the `WebView` fetch the page (again) for itself to be able to display it.

It's a pity that there's no solution that is easier and more efficient. Sorry!
