### ISSUE TITLE
Cannot play Fullscreen Video from the webPage ?!

### ISSUE THREAD

**Issue by xCodeSoul** [delight-im/Android-AdvancedWebView#109]
Hello,

When I press the fullscreen button on any video or double tab it,, the screen turns white

how I can get full screen button working?

Best regards

**Comment by ocram** [comment]
Please see https://github.com/delight-im/Android-AdvancedWebView/issues/45, https://github.com/delight-im/Android-AdvancedWebView/issues/73 and https://github.com/delight-im/Android-AdvancedWebView/issues/84
