### ISSUE TITLE
once i set desktopview to true it works fine,but second time its loading mobileview

### ISSUE THREAD

**Issue by A4Android** [delight-im/Android-AdvancedWebView#111]

**Comment by ocram** [comment]
This can only happen if you modify the `WebSettings` instance returned by `getSettings()` yourself, somehow, so that it loses the required values.

**Comment by A4Android** [comment]
But when i close the app and open it again i should open the webview in desktop view ... because i destroy the webview when exiting from app.after uninstalling the app it works fine but only for the first time..

**Comment by A4Android** [comment]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        init();
        webView.setListener(this, this);
        LoadUrl();
    }

private void init()
    {
        webView = (AdvancedWebView)findViewById(R.id.webview);
    }

private void LoadUrl()
    {

        webView.loadUrl(url);
        webView.setDesktopMode(true);
    }

**Comment by ocram** [comment]
You should switch the two lines

```java
webView.loadUrl(url);
webView.setDesktopMode(true);
```

so that it becomes

```java
webView.setDesktopMode(true);
webView.loadUrl(url);
```

Apart from that, you have to call `setDesktopMode` whenever your `Activity` (or at least `AdvancedWebView`) instance is re-created. But it seems you're already doing that.
