### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by prakashbalab24** [delight-im/Android-AdvancedWebView#112]
Uploading an image from the local storage is not working.

- Clicking "choose file" is opening file manager but the file is not updating in view, its still showing "no file chosen".

Note:
1. Permission is given in manifest. 
2. Even i tried to give read storage permission manually (version M and N).

**Comment by ocram** [comment]
What Android version are you actually running this on? You talked about versions M and N, so you've really made sure that you're not trying to run this on 4.4?

Apart from that, you must absolutely make sure that you followed what is written in the README. Especially the callbacks, e.g. `onActivityResult`, are important to implement correctly, as described.

**Comment by prakashbalab24** [comment]
Thanks.. Thats my mistake. Now its working fine.
