### ISSUE TITLE
Resize Webview when softKeyboard open

### ISSUE THREAD

**Issue by bensventures** [delight-im/Android-AdvancedWebView#113]
I have been AdvancedWebView successfully for a while now but I recently came upon a behaviour that is proving difficult to resolve. 

I have an input field at the bottom of a page. On focus the softKeyboard opens but hide the input and the view does not allow for scroll, making the user type blindly.

I have tried some of the solutions found after some googling, mainly involving `android:windowSoftInputMode="stateHidden|adjustResize"` but no success so far.

Any idea on how to work around this issue?

**Comment by bensventures** [comment]
Found out what the problem was, sorry for the false alarm. I was setting my app to full screen with 

`this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);`

and apparently that's not compatible with `adjustResize`. After removing the above line from MainActivity, the WebView correctly scrolls when the keyboard is opened.

**Comment by ocram** [comment]
No problem, thanks a lot for the helpful clarification!
