### ISSUE TITLE
Image names are altered.

### ISSUE THREAD

**Issue by ronakmehta1989** [delight-im/Android-AdvancedWebView#12]
It works fine for me but it alter the image name.
When I select image from browser "Attach file" , It alter the image name something like "image%xxxx" 
Here xxxx are any random numbers.

Note : I'm selecting image with default name like "sample.png".

I've tried to choose different image but problem is same.

Any solution ?

**Comment by mwaclawek** [comment]
Thanks for your feedback!

Unfortunately, there is no solution to this problem, it seems. You can't rely on the file names that you received from the client. This is true in general. They may even be obfuscated for privacy reasons.

So the `WebView` implementation has full control over the upload itself and thus the file name. At least for Android 4.4.*, we can confirm that the file names are altered by Android and you can't do anything about this. Sorry!

**Comment by ronakmehta1989** [comment]
@mwaclawek  Thank you for the response.
