### ISSUE TITLE
onDownloadRequested not triggered

### ISSUE THREAD

**Issue by mmalisz** [delight-im/Android-AdvancedWebView#123]
Hi there,
I've got a Galaxy Tab A7 T285 with stock 5.1.1.

The onDownloadRequested doesn't seem to be triggered on that device. The debugger won't event enter that method. However, it works as intended on vanilla 5.1.1 running on Nexus 4.

I've tried both 3.0.0 and master versions -- same result.

**Comment by ocram** [comment]
So you're running this on two real devices, both with Android 5.1.1, and on one of these devices it's working fine while on the other one it's not? That's strange, indeed.

The [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) is up-to-date as well on both devices?

What you could do is add the following call right after creating the WebView instance:

```java
myWebView.setDownloadListener(new DownloadListener() {

	@Override
	public void onDownloadStart(String url, String userAgent, String contentDisposition, String mimeType, long contentLength) {
		// log this ...
	}

});
```

It would be interesting to know if that callback is called on both devices. Please note that this disables the other callback that you've been testing previously. But this one here is on a lower level, so more helpful for debugging.

**Comment by mmalisz** [comment]
Cannot tell about the Nexus device as it is not mine, but the Galaxy Tab is up to date, as it was purchased today and I've updated everything that is possible.

I will test it next week as soon as I'm back at work.
If i'll get some free time, I will try this code on my Moto G3 running CM13 (Android 6).

**Comment by mmalisz** [comment]
Sorry for a late response. Dunno what happend, but it started working without any changes of the code. Moreover, I haven't even reinstalled the app.
I think it can be closed for now.

**Comment by ocram** [comment]
No problem!

Glad this issue resolved itself then, at least we do know now that there's no bug here :)

Thanks for your reply!

**Comment by mmalisz** [comment]
Littile of topic, if I may. Have you managed to make file type input work on KitKat? Not by this component, but at all.

**Comment by ocram** [comment]
Yes, there are a few solutions:

 1. Add a [JavaScript interface](https://developer.android.com/reference/android/webkit/WebView.html#addJavascriptInterface(java.lang.Object,%20java.lang.String)) which lets your Java code and the JavaScript code inside the WebView communicate. If you want to initiate a file upload, let the JavaScript inside your WebView tell the Java code inside your Android app that you want to pick a file. In Java, you can then open a dialog that lets the user select a file from the device. After that, you encode the selected file in Base64 (in Java) and send the Base64 string to the WebView using your JavaScript interface.
 2. You can bundle [Crosswalk](https://crosswalk-project.org/), an alternative WebView implementation.
 3. You can just wait for Android 4.4 to go away, which [is happening](https://developer.android.com/about/dashboards/index.html) (slowly).

**Comment by mmalisz** [comment]
Thanks for the tips!
