### ISSUE TITLE
Bag AdvancedWebView + admob InterstitialAd

### ISSUE THREAD

**Issue by WooDoo2** [delight-im/Android-AdvancedWebView#124]
Hello
When I use AdvancedWebView then not work links on Full Screen Ad
InterstitialAd showed but links not work
show InterstitialAd  from another activity - still does not work
Help please

**Comment by ocram** [comment]
1. Is your version of this library up-to-date?
 1. Can you verify this on a real device, as opposed to an emulator?
 1. Is [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) up-to-date on your device?

Apart from that, can you explain the problems in detail or show some screenshots? Perhaps https://github.com/delight-im/Android-AdvancedWebView/issues/122 is related to your problem as well.

**Comment by WooDoo2** [comment]
1 - yes test  library up-to-date
2 - yes test on real device
3 - no update
Decision. I am not called advancedWebView.onPause() and it work
Big thanks

**Comment by ocram** [comment]
Thanks, happy to hear that you were able to resolve this!
