### ISSUE TITLE
FileChoose work in debug, not on smartphone

### ISSUE THREAD

**Issue by TremalJack** [delight-im/Android-AdvancedWebView#125]
Hi,

Im using your library in a Project:

```
apply plugin: 'com.android.application'

 android {
    compileSdkVersion 22
    buildToolsVersion '25.0.0'
    defaultConfig {
        applicationId "xxx.xxxx"
        minSdkVersion 22
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile 'com.github.delight-im:Android-AdvancedWebView:v3.0.0'
}
```

So the project is this:
--- I have my "webapp" in a server
--- The Android App connect to the webapp and show everything in fullscreen
--- In a section the clients have the possibility to write a comment and select 1 ore more files and then send them
--- The "email" work in a php class, it work perfect, I tested it from pc, notebook, tables and phones from every kind of browser

So... now... in to the android app, in debug, everything work, so the web view show the website, the file choose work, I press submit and then I receive the email with the body message I wrote and with the files I selected.

Then I go to compile the signed-apk, I install everything and when I go do the same stuff of before, I receive the email without the files.

I thought was a "permission" issue, so I added the permissions into the androidmanifest, I tried again... and nothing I have always the same issue...

Im working with API 22 to be avaiable to old version too, I have android 6.0.1. on my galaxy s6 edge plus, then I thought was a version problem, so I changed everything to be compiled in the same version, but the problem persist.

Then I back to work and compile into API 22 Android version 5.0

Can you help me to fix the problem?

**Comment by ocram** [comment]
The reason could be that you either forgot the ProGuard rules (see README) or they have not been enabled correctly in the build process. Could you check this?

**Comment by TremalJack** [comment]
So I have add this:

-keep class * extends android.webkit.WebChromeClient { *; }
-dontwarn im.delight.android.webview.**


into:

buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }


right?

**Comment by ocram** [comment]
Oh, well, `minifyEnabled false` should already be enough. Otherwise, you'd have to add those rules to `proguard-rules.pro`.

So it's still not working?

Try to debug this with a minimal example, not your complete application. Try the file upload only. There must be *some* reason why it's not working on your phone.

**Comment by TremalJack** [comment]
O yes, now work perfectly, the issue was on missing pro-guard rules.

A little question, is possible clear the cache everytime the user haven't the app working?

**Comment by TremalJack** [comment]
Or more better... reset the cache everytime the app go to be active

**Comment by ocram** [comment]
Great that it works, thanks!

In order to clear the cache, try calling

```java
myWebView.clearCache(true);
```

before loading any URL. In order to disable the cache entirely, try

```java
myWebView.getSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);
```

also before loading any URL.
