### ISSUE TITLE
Show/Download PDF

### ISSUE THREAD

**Issue by TremalJack** [delight-im/Android-AdvancedWebView#126]
Hi again,

I have a new questio, into my webapp I have some direct urls to open/download some pdf files, the button are just some standard "a href" they work fine on every type of device.
But on the app, if I click on those buttons, the progressbar show me the right loading, but nothing appear/download.

How I can show those PFD inside the advanced webview or just download them?

I have already the onDownloadRequested functione declare into the code:

```
  @Override
    public void onDownloadRequested(String url, String suggestedFilename, String mimeType, long contentLength, String contentDisposition, String userAgent) {
    }
```

**Comment by ocram** [comment]
You actually have to write some code inside of that callback. See the README, which shows that as well.

Apart from that, try with "normal" downloads first, i.e. not those triggered via a `download` attribute but those triggered by HTTP headers or due to their file types.
