### ISSUE TITLE
Show html stored page on Page Errors or No connection

### ISSUE THREAD

**Issue by TremalJack** [delight-im/Android-AdvancedWebView#128]
Hi,

It's possible show a stored html page if phone haven't connection or if is present some errors?

If yes, How I can do it?

**Comment by ocram** [comment]
You should be informed about any errors in the `onPageError` callback. If that happens and the callback is called, you should be able to display a HTML page from your `assets` folder as shown in the README:

```java
myWebView.loadUrl("file:///android_asset/html/index.html");
```

Alternatively, you can check whether there is an active internet connection using the corresponding Android APIs.

Does that work?
