### ISSUE TITLE
How to fix "No connection" error?

### ISSUE THREAD

**Issue by rignaneseleo** [delight-im/Android-AdvancedWebView#129]
Hi, I'm using your WebView for my app [SlimSocial for Facebook](https://github.com/rignaneseleo/SlimSocial-for-Facebook).
Some users have written me that when they use my app, they receive the Facebook message ["no internet connection"](https://dl.xda-developers.com/4/1/1/6/4/4/7/Screenshot_20170418-075350.png?key=Y9GVtuEb-fCkhWnOm-LytA&ts=1492867127).

Without your webview all works. What could it be? I think that the webview blocks some Facebook connections but I have no idea why and where I can fix it.

Thank you

**Comment by ocram** [comment]
Thanks!

The link for that attachment has expired, it seems. So it cannot be viewed anymore.

So what is Facebook's "No internet connection" message exactly? Is the internet connection really gone? In that case, that would hardly be an error in this library and you could just check for an active internet connection with the respective Android APIs. If the connection is not actually gone, why is that message shown by Facebook?

The latter seems to be your question as well. But without any information about that error message shown by Facebook, and without any information on how to re-produce this, fixing this (whatever it is) will be hard.

> Without your webview all works.

What does that mean? You can't just have the same functionality by removing this library. Did you replace this library with Android's built-in WebView and you've been able to verify then that the error does not occur anymore? Or did you refer to normal usage of Facebook in one's favorite browser (where this doesn't seem to happen)?

**Comment by rignaneseleo** [comment]
The screen error is [this ](https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-9/18485261_1489819991068804_7393663388489017350_n.jpg?oh=911040286b4d533d771d80975d62dfe5&oe=59AD732D).
The Android built-in WebView seems work without problems!

**Comment by ocram** [comment]
Sorry, have never seen this and have really no idea what is causing Facebook to show this.

The logic that decides when to show this is certainly implemented in site-specific code by Facebook, so debugging what must happen for Facebook to show this is probably the only solution available here.

**Comment by ocram** [comment]
Please re-open if you find out or know what we can do here. Thanks!
