### ISSUE TITLE
New methods on API 21

### ISSUE THREAD

**Issue by jordim** [delight-im/Android-AdvancedWebView#13]
Hi,

Is there some plan to introduce the methods introduced on WebView (API 21) or this will be up to the user-developer?

I'm mean something like

```
@TargetApi(Build.VERSION_CODES.LOLLIPOP)
public void acceptThirdPartyCookies(boolean enabled) {

  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
      CookieManager cookieManager = CookieManager.getInstance();
       cookieManager.setAcceptThirdPartyCookies(this, enabled);
  }
}
```

I can create a pull request if needed.

Great library :)

**Comment by mwaclawek** [comment]
Thanks!

This specific feature has been added now:
https://github.com/delight-im/Android-AdvancedWebView/commit/d0f3fe324fbd53a11d277acc45fc20425bd2fbdd

Please report if this is what you had in mind :)

For other APIs, please open separate issues.
