### ISSUE TITLE
can't find referenced method 'void onUnhandledInputEvent in library class android.webkit.WebViewClient Proguard

### ISSUE THREAD

**Issue by AbreuY** [delight-im/Android-AdvancedWebView#135]
I'm getting this error when i try to use proguard. I have put the code in proguard:

```
-keep class * extends android.webkit.WebChromeClient { *; }
-dontwarn im.delight.android.webview.**
```
But still i'm getting this warning.

Warning: im.delight.android.webview.AdvancedWebView$1: can't find referenced method 'void onUnhandledInputEvent(android.webkit.WebView,android.view.InputEvent)' in library class android.webkit.WebViewClient

**Comment by ocram** [comment]
Thanks!

Could that be related to https://github.com/delight-im/Android-AdvancedWebView/issues/83?

What Android version are you running this on?

**Comment by AbreuY** [comment]
I'm compiling with API level 24. But still i haven't solved this. Yes is related to https://github.com/delight-im/Android-AdvancedWebView/issues/83

**Comment by ocram** [comment]
Sorry for the problems!

Let's track it in the other (related) issue then, though.
