### ISSUE TITLE
unable use camera on upload form

### ISSUE THREAD

**Issue by ciberfox** [delight-im/Android-AdvancedWebView#137]
Hello,
On an HTML page with standard loader integrated into a form, you do not have the choice of using the file manager or camera.

An example of my html code:
 <input class="w3-input" type="file" name="pic" accept="image/*">

The devices I'm testing the app are:
Asus zenfon2 android M
Kindle Fire 7 2017

**Comment by ocram** [comment]
See https://github.com/delight-im/Android-AdvancedWebView/issues/10, https://github.com/delight-im/Android-AdvancedWebView/issues/16, https://github.com/delight-im/Android-AdvancedWebView/issues/20 and https://github.com/delight-im/Android-AdvancedWebView/issues/81
