### ISSUE TITLE
WebView doesn't display youtube videos

### ISSUE THREAD

**Issue by iamabeljoshua** [delight-im/Android-AdvancedWebView#138]
I am facing an issue with the library. Youtube videos aren't displayed but the music plays. any idea how I can work around this?

**Comment by ocram** [comment]
What Android version is the device or emulator running on where you tested this?

Did you try to use fullscreen mode?

Does the video show up in default (non-fullscreen) mode?

What about video on other sites, e.g. `vimeo.com`?

**Comment by ferguson-abel** [comment]
Thanks for your reply, I tested it on Android Nougat, I haven't tried full-screen mode yet as my app is not meant for watching videos or a replacement for web browsers..

Yes the video is not on full-screen mode for now. 

I tried vimeo and it's the worst... It displays a blank page when the video is playing.

**Comment by ocram** [comment]
Thanks!

There are a few other issues here related to video. You can search them, but they may not really be related after all. Most are about fullscreen mode.

Can you try on Marshmallow or Lollipop instead? Does that change anything?

**Comment by ferguson-abel** [comment]
Ok I will give it a try...  thanks

**Comment by ferguson-abel** [comment]
I tried it on android version 4.4.... this seems to be an issue on the version of android Marshmallow and above...

**Comment by ocram** [comment]
So on Android 4.4, video is showing up, while on Android 5.0 through 7.0, video is not visible (black?) but only audio plays? Is that correct?

Did you really see that behavior on 5.x, 6.x *and* 7.x? Can you perhaps try different devices for one of those versions?

**Comment by igorfastronicorrea** [comment]
Hi Ocram,

I'm testing in Android 7.0, 6.0 and 5.1, it's not working at all. When click in Full Screen, the audio continue but the video is black or white. Any idea how fix this?

**Comment by A86S** [comment]
facing same issue any success ?

**Comment by ocram** [comment]
@igorfastronicorrea (and perhaps @A86S), the fullscreen solution is discussed in https://github.com/delight-im/Android-AdvancedWebView/issues/84

This issue right here originally was about non-fullscreen problems, as far as I understood.
