### ISSUE TITLE
how to get rid of get_meta_data?

### ISSUE THREAD

**Issue by Nareshvelmurugan** [delight-im/Android-AdvancedWebView#139]
Thanks a lot for your code. I'm running the app with my url. whenever I refresh or go sub-links, it popups the website meta data and also message like finished loading. 
Then, if I navigation from one page to another page or url, it freezes on the white screen or takes too long too.
could you please help me how do I get rid of them? Thanks in advance

**Comment by ocram** [comment]
What is `get_meta_data`?

This library does not provide any dialogs in the situations that you described. So you either used the included sample or another pre-written sample for your app, didn't you?

Just follow the README and only show dialogs when desired.
