### ISSUE TITLE
Android 4.4.2 File Upload Problem.

### ISSUE THREAD

**Issue by VeriDigital** [delight-im/Android-AdvancedWebView#141]
I am having a file upload problem with this plugin on Android 4.4.2

* File selection button does not respond. 
* No problem with application permissions. Device Samsung s4. 
* 4.1.x, 4.2.x and 5.x with above not having problem. 

Is there anyone who knows about the problem?

**Comment by ocram** [comment]
See https://github.com/delight-im/Android-AdvancedWebView/issues/4
