### ISSUE TITLE
Download youtube video

### ISSUE THREAD

**Issue by dtdaft** [delight-im/Android-AdvancedWebView#142]
Hi everyone,
I want to know if it's possible to handle or force download of Youtube video in this format thru AdvancedWebView:

https://r5---sn-4g5e6ns7.googlevideo.com/videoplayback?expire=1501449754&ratebypass=yes&itag=22&ei=uvl9WaauG7-2cdCisPgH&mn=sn-4g3e6ns4&dur=3048.060&ipbits=0&mm=31&key=yt5&pl=19&id=o-ACbsBkkzRSTZUTcfQzlQ0VAAaRSIUQlXrssh0aOAGIKm&mv=u&sparams=dur%2Cei%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&source=youtube&ms=au&mime=video%2Fmp4&requiressl=yes&signature=9041E720525A55EEB524F67F0A28DF198DF9354D.5F5F7DF3D4A57764F2399B0BD248F1E383BF5F0A&ip=217.162.62.99&mt=1501427445&lmt=1475860904871589&title=Searching-for-sugar-man-Rodriguez-full-soundtrack

If anyone have a solution,

Regards,

**Comment by ocram** [comment]
This is not included in this library. It's out-of-scope and thus a separate solution is required.
