### ISSUE TITLE
Cookies are lost in webview when activity is destroyed (session gone)

### ISSUE THREAD

**Issue by DenLangeKilde** [delight-im/Android-AdvancedWebView#143]
I am trying to make my webview remember the cookies across activities/sessions. 
I have tried a lot of different things. Some of them are:

 - Using CookieManager to retrieve the cookies and adding them both throud loadUrl and CookieManager
 - CookieSyncManager (deprecated)

The webview is a part of a fragment and the cookies are not lost when only the fragment is destroyed, only when the activity is.

    private void init() {
            if (url != null) {
                webview.setListener(getCustomActivity(), new AdvancedWebView.Listener() {
                    @Override
                    public void onPageStarted(String url, Bitmap favicon) {
    
                    }
    
                    @Override
                    public void onPageFinished(String url) {
                    }
    
                    @Override
                    public void onPageError(int errorCode, String description, String failingUrl) {
    
                    }
    
                    @Override
                    public void onDownloadRequested(String url, String suggestedFilename, String mimeType, long contentLength, String contentDisposition, String userAgent) {
    
                    }
    
                    @Override
                    public void onExternalPageRequest(String url) {
    
                    }
                });
    
    
                webview.getSettings().setCacheMode(WebSettings.LOAD_CACHE_ELSE_NETWORK);
                webview.setCookiesEnabled(true);
                webview.loadUrl(url);
                urlLoaded = true;
}

It is probably me, doing something wrong, but I can't figure out how to preserve the cookies across activities

**Comment by ocram** [comment]
Feel free to share your solution if it may be helpful to others as well. Thanks!

**Comment by DenLangeKilde** [comment]
I was too quick. I thought I got it to work, but I still have the problem. I will reopen and elaborate the issue.
I have posted a question on StackOverflow with this, so here it is, directly from StackOverflow:

------------------------------------------------------------------------
I have been very confused with my implementation of webview in my android app. The problem is that cookies aren't stored or retrived correctly in my webview.

First, here is my code for the webview, which is pretty simple:

```
private AdvancedWebView         webview;

private void init(String url) {
        if (url != null) {
            webview.setWebViewClient(new WebViewClient() {
                @Override
                public boolean shouldOverrideUrlLoading(WebView view, String url) {
                    return false;
                }
            });

            if (Build.VERSION.SDK_INT == 21) {
                CookieManager.getInstance().setAcceptCookie(true);
            } else {
                CookieManager.getInstance().acceptThirdPartyCookies(webview);
            }

            webview.loadUrl(url);
        }
    }
```
My problem is best described like this:

- I open the Activity and Fragment containing the webview.
- I change something on the website, setting a cookie (a dialog is closed permanently).
- I go back, killing the fragment and activity.
- Then I open up the fragment with the webview again, seeing that the cookie is still set (Website is not showing the dialog based on the cookie set).
- I repeat this procedure X amount of times until it the cookie is suddenly not set (website is showing the dialog again).

This happens after approximately 40 seconds, no matter if I open up the webview screen 2 or 10 times.

I can't seem to get this behaviour. So how do I get the webview to handle the cookies correctly.

**Comment by ocram** [comment]
First, `setWebViewClient` with a custom `WebViewClient` which always returns `false` from `shouldOverrideUrlLoading` should simply be the default. As far as I can see, you can remove it without any effects.

Second, the option

```java
CookieManager.getInstance().setAcceptCookie(true);
```

should be the default as well. You can probably remove it, too. Apart from that, any reason why you're setting this on API level 21 only?

Third, the call

```java
CookieManager.getInstance().acceptThirdPartyCookies(webview);
```

has no effect as it just *reads* the setting. You have to use

```java
CookieManager.getInstance().setAcceptThirdPartyCookies(webview, true);
```

instead to *set* it. Again, any reason why you're calling this on API levels `!= 21` only? It should probably be `>= 21`.

That being said, cookies should actually work by default, out of the box. Can you just try removing all of your cookie-related code?

**Comment by DenLangeKilde** [comment]
Thanks for the quick reply.
The reason for the "== 21" check, was that I read the this particular API level needed to be dealt with different,

I have tried and remove it all, but the same weird behaviour regarding cookies still remains. Could it have something to do with new sessions being created everytime the webview is inflated and thereby confusing the webview cookie handling?

**Comment by ocram** [comment]
Any behavior that you're seeing is not specific to this library and any problems will be due to the underlying `WebView` component and its API. So we won't really be able to help here. Sorry!

You should definitely try cookie support with a minimal example first and check if you have special requirements, e.g. cookies on a `file://` scheme.
