### ISSUE TITLE
Can I set a custom location for storing cookies

### ISSUE THREAD

**Issue by DenLangeKilde** [delight-im/Android-AdvancedWebView#145]
I found out that my cookies are being cleared/garbage collected (most likely) by java's internal HttpClient as a result of some of my network code.

Is there a way to set a seperate path/location for storing the cookies?

This is what I have tried until now:
```
webview.setWebViewClient(new WebViewClient() {
                @Override
                public void onPageFinished(WebView view, String url) {
                    if (getCustomActivity() != null) {
                        CookieSyncManager.createInstance(getCustomActivity()).sync();
                    }
                }
            });
            webview.getSettings().setAppCachePath("/data/data/"+getActivity().getPackageName()+"/webview_cookies/");
            webview.loadUrl(url, true);
```

 Any help will be greatly appreciated. And thanks for a great library btw.

**Comment by ocram** [comment]
This is not a feature built into this library right now, and there are no plans to add it. Sorry!

You can look into the original [WebView API](https://developer.android.com/reference/android/webkit/WebView.html) in order to check if this might be possible.

**Comment by DenLangeKilde** [comment]
I came up with a solution myself. It's working, but still needs some adjustments etc. You can find it here, if it could be useful to you somehow:
https://stackoverflow.com/questions/45610766/android-webview-cookies-are-cleared-garbage-collected-after-some-time-can-i-se/45631720#45631720

Again, thanks for a great library :)

**Comment by ocram** [comment]
No problem, thanks for your appreciation and for sharing your solution!
