### ISSUE TITLE
Possibility to iOS platform

### ISSUE THREAD

**Issue by renandiett** [delight-im/Android-AdvancedWebView#148]
Hello guys! Thank you so much for sharing this awesome tool! I had purchased another tool on ThemeForest but does not solved my problem: it can't do the trick with html input:file.

Now I'm wondering if you can make the same tool but for iOS platform. If you have another tool that make it possible, please tell me, I will be so happiness. 👍

**Comment by ocram** [comment]
Thank you!

Unfortunately, there won't be any iOS version in the foreseeable future. Really sorry!
