### ISSUE TITLE
Modify Page Transition/Animation

### ISSUE THREAD

**Issue by NinoFav** [delight-im/Android-AdvancedWebView#149]
Hi! First I want to thank you for sharing this project!

I want to know how to delete or change the dark screen between each page visited or link clicked?
How to replace them by a right slide transition and left slide transition when users use the back button (previous page)?

I tried to find a general solution on forums like StackOverFlow but it don't work on this implementation..

Thank you in advance.

**Comment by ocram** [comment]
Thank you!

Transitions and animations are not related to this library and can be applied to your application separately.

You might use the event callbacks such as `onPageStarted` useful to determine when to start/end your transition or animation.
