### ISSUE TITLE
Hidden Fields are shown!

### ISSUE THREAD

**Issue by khaledkhj** [delight-im/Android-AdvancedWebView#153]
Thank you for the great work on this library.

I am having one issue while using the library!
I could see all hidden inputs or field while loading html content!

Any help please?

Thank you.

**Comment by khaledkhj** [comment]
Sorry, 
nothing to do with this!

I didn't notice that the original page was handling those hidden field that way!

You can close this issue!

**Comment by ocram** [comment]
No problem!
