### ISSUE TITLE
cant download anything

### ISSUE THREAD

**Issue by aaqibpk** [delight-im/Android-AdvancedWebView#155]
When i click on something like an mp3 file to download. The app doesn't download anything.

Tried with this first
```
public void onDownloadRequested(String url, String suggestedFilename, String mimeType, long contentLength, String contentDisposition, String userAgent) { }

```

then i put following code inside onDownloadRequested

```
        if (AdvancedWebView.handleDownload(this, url, suggestedFilename)) {
            // download successfully handled
        }
        else {
        }
    }
```

After putting the following code the app just stop running when i click on download button

Thank you please help me asap

**Comment by ocram** [comment]
Let’s keep a single issue for the discussion on this question. Thank you!

https://github.com/delight-im/Android-AdvancedWebView/issues/147
