### ISSUE TITLE
Some Page not reload

### ISSUE THREAD

**Issue by dhavalkba** [delight-im/Android-AdvancedWebView#157]
I implemented this library for better webview but facing one issue in my app for reload current page,
for reload current page i call advanceWebview.reload() it working perfectly but some page not reload.

Please give me solution.

Thanks

**Comment by ocram** [comment]
> but some page not reload

What does that mean exactly? How does it show?

Are those pages that do not reload properly perhaps results of POST requests?

Apart from that, you could also try the following:

```java
myWebView.loadUrl("javascript:window.location.reload(true);");
// or
myWebView.evaluateJavascript("window.location.reload(true);", null);
```

Does that help?

**Comment by nicojmb** [comment]
in my app "window.location.reload();" do not work.

**Comment by nicojmb** [comment]
Fixed, i run webview.reload() from ui trhead and works

`runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    _webview.reload();
                }
            });`

**Comment by ocram** [comment]
@nicojmb Thanks a lot for sharing your solution!
