### ISSUE TITLE
set webpage with to match parent

### ISSUE THREAD

**Issue by norrisboat** [delight-im/Android-AdvancedWebView#158]
I don't want elements in my html to go beyond the width of the phone's screen in other words prevent horizontal scrolling. How will I achieve this. I've tried with css which works but still there is an empty space enabling horizontal scrolling.

**Comment by ocram** [comment]
1. What does it currently look like? Can you share an image perhaps? Where is that “empty space” enabling horizontal scrolling?
 1. How does the same page look like in Chrome on Android? What about horizontal scrolling there?
 1. What’s your layout for the screen on Android? What about your `android:layout_width` and `android:layout_height`, specifically?

**Comment by norrisboat** [comment]
More CSS helped me get the results I wanted. Thanks very much

**Comment by ocram** [comment]
Good to hear that, thanks!
