### ISSUE TITLE
Choose an action for input

### ISSUE THREAD

**Issue by neonmate** [delight-im/Android-AdvancedWebView#16]
Hello,
I want to use the camera as input device for images. For the HTML I tried following approaches:

     <input type="file" accept="image/*">
     <input type="file" accept="image/*;capture=camera">
     <input type="file" accept="image/*" capture="camera">

In the Android Browser it works great with API Level 15 and 21. But in the WebView, it is not possible to use the camera directly, like you know from a native app. 

**API 15**
https://cloud.githubusercontent.com/assets/2969758/6741622/69f1b7c2-ce89-11e4-995b-7f5af0d596a8.png
https://cloud.githubusercontent.com/assets/2969758/6741623/69f6f4f8-ce89-11e4-9668-b37db04c2c31.png

**API 21**
https://cloud.githubusercontent.com/assets/2969758/6741624/69f87422-ce89-11e4-9528-3d4adb67cb76.png
https://cloud.githubusercontent.com/assets/2969758/6741625/69fa6c78-ce89-11e4-8fc4-f58da3d25a6a.png

I also added the camera permission to the manifest:

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.FLASHLIGHT"/>

Perhaps you know, how I have to change this in der WebView. Thanks!

**Comment by mwaclawek** [comment]
Thanks for this request!

Adding the media capture features is possible, but actually not as easy as one might think:
https://github.com/delight-im/Android-AdvancedWebView/issues/10

So this requires modifications to the Java source code from this library. The `WebView` class does not provide all features that full-featured browsers such as Firefox and Chrome offer, at least not without further additions.

This means that, in addition to providing the element attributes in your HTML, you would have to modify the source code of this library for your use case -- at least until we have this feature here.

**Comment by Vissanu** [comment]
Hello @mwaclawek 
I'm new android developer. I have some question about your libs.
Is this libs has a CookieSync? I wanna pass a cookie to URL for auto login by token.
Something like this code : 
CookieSyncManager.createInstance(ActivityName.this);
        CookieManager cookieManager = CookieManager.getInstance();
        cookieManager.removeSessionCookie();
        String token = session.User_status;
        String cookieString = "s_admin="+ token;
        cookieManager.setCookie("lhttp://abc-site.com", cookieString);
        CookieSyncManager.getInstance().sync();

But it isn't work for me. Can you help me? Thanks @mwaclawek.
