### ISSUE TITLE
Enable ZOOM in and OUT

### ISSUE THREAD

**Issue by phx255** [delight-im/Android-AdvancedWebView#160]
It's possible? would be great for some websites.
Thanks!

**Comment by ocram** [comment]
What about the following built-in methods?

 * [WebSettings#setDisplayZoomControls(boolean)](https://developer.android.com/reference/android/webkit/WebSettings.html#setDisplayZoomControls(boolean))
 * [WebSettings#setBuiltInZoomControls(boolean)](https://developer.android.com/reference/android/webkit/WebSettings.html#setBuiltInZoomControls(boolean))
 * [WebSettings#setSupportZoom(boolean)](https://developer.android.com/reference/android/webkit/WebSettings.html#setSupportZoom(boolean))

These can be called on the object returned from the following method call:

```java
myWebView.getSettings();
```
