### ISSUE TITLE
Website request FullScreen makes webview crash

### ISSUE THREAD

**Issue by vrgomes** [delight-im/Android-AdvancedWebView#163]
Hi,
When a website requests full screen the webview became unresponsive.
Element.requestFullscreen()
For example if you open: https://davidwalsh.name/demo/fullscreen.php
And click to open in Full Screen the webview stop working.

Anyone know the motive for this to happen? On the console nothing shows and on Chrome it works good.

Greetings.

**Comment by ocram** [comment]
What Android version did this happen with? Can you reproduce that behavior with other devices (that have different Android versions)?

**Comment by vrgomes** [comment]
I managed to fix it: https://github.com/akhgupta/WebviewVideo

**Comment by ocram** [comment]
Thanks, implementing two additional methods is enough to make this work, see https://github.com/delight-im/Android-AdvancedWebView/issues/84.
