### ISSUE TITLE
tel: and sms: links problem

### ISSUE THREAD

**Issue by VeriDigital** [delight-im/Android-AdvancedWebView#168]
Hello.

When you click on links such as tel: or sms: the application gives the error: address is not found. 

I want open dial or sms application when tel: or sms: link is clicked.

How can I fix?

**Comment by ocram** [comment]
You may want to override `shouldOverrideUrlLoading` in your `WebViewClient`. If the URL that you receive there starts with one of your prefixes (i.e. `tel:` or `sms:`) you handle that case specially (e.g. by starting an `Intent`) and return `true`. Otherwise, do nothing and return `false`.

**Comment by ranahyder87** [comment]
I'm using Android-AdvancedWebView. How I can use `shouldOverrideUrlLoading` and `WebViewClient` ?

**Comment by ocram** [comment]
A solution has been implemented now so that support for these URL schemes is built-in from now on. Please see [this thread](https://github.com/delight-im/Android-AdvancedWebView/pull/223) for more information and for details on how the solution has been implemented, in case you’re interested.
