### ISSUE TITLE
[ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver

### ISSUE THREAD

**Issue by Z644912187** [delight-im/Android-AdvancedWebView#170]
[ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver

**Comment by ocram** [comment]
Did you just find this in the logs? There’s no wrong behavior of the library? If so, you can simply ignore it.

As per [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=662040), with [this specific cause](https://bugs.chromium.org/p/chromium/issues/detail?id=662040#c50) and [this solution](https://bugs.chromium.org/p/chromium/issues/detail?id=662040#c56), it appears fixed.

**Comment by yerevin** [comment]
@Z644912187 how did you fixed this issue? i have same in my cordova based app

**Comment by ocram** [comment]
@yerevin Did you read above? It appears unlikely that this is actually a real bug for your application. Most likely, you can simply ignore it. It has been a bug in the Android OS and its Chrome-backed WebView implementation, which has since been fixed.

**Comment by yerevin** [comment]
okey, my bad looks like it has no bad impact on app work
