### ISSUE TITLE
Geolocation doesn't work in webview

### ISSUE THREAD

**Issue by LevelMaxBR** [delight-im/Android-AdvancedWebView#173]
Hello, unfortunately GeoLocation does not work because I can not get the message to allow localization. I have already enabled the permissions and marked as "true" WebView.setGeolocationEnabled (true);

sorry my english
-Thank you for making this beautiful work available.

**Comment by ocram** [comment]
Where do you have the line

```java
mWebView.setGeolocationEnabled(true);
```

exactly? In `onCreate` or some similar method? Before any call to `loadUrl`?

And the element

```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

has been added to the correct manifest file?

Could you add

```xml
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

as well, just to be sure?

On what type of device have you been testing this? Could you test this on a device (or on an emulator) with Android 4.x or 5.x?

(Your English is perfect, and thanks for your appreciation!)

**Comment by KeyboardSan** [comment]
Hey, I was having the same problem. And I can see it is a little bit late but here is my solution which worked.
Add this code in your onCreate function:
`mWebView.setWebChromeClient(new WebChromeClient(){
            @Override
            public void onGeolocationPermissionsShowPrompt(String origin,
                                                           GeolocationPermissions.Callback callback) {

                callback.invoke(origin, true, false);
            }
        });
        // ...
        checkLocationPermission();`

And then outside it you add this:
`public static final int MY_PERMISSIONS_REQUEST_LOCATION = 99;

    public boolean checkLocationPermission() {
        if (ContextCompat.checkSelfPermission(this,
                Manifest.permission.ACCESS_FINE_LOCATION)
                != PackageManager.PERMISSION_GRANTED) {

            // Should we show an explanation?
            if (ActivityCompat.shouldShowRequestPermissionRationale(this,
                    Manifest.permission.ACCESS_FINE_LOCATION)) {

                // Show an explanation to the user *asynchronously* -- don't block
                // this thread waiting for the user's response! After the user
                // sees the explanation, try again to request the permission.
                new AlertDialog.Builder(this)
                        .setTitle(R.string.title_location_permission)
                        .setMessage(R.string.text_location_permission)
                        .setPositiveButton(R.string.ok, new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialogInterface, int i) {
                                //Prompt the user once explanation has been shown
                                ActivityCompat.requestPermissions(MainActivity.this,
                                        new String[]{Manifest.permission.ACCESS_FINE_LOCATION},
                                        MY_PERMISSIONS_REQUEST_LOCATION);
                            }
                        })
                        .create()
                        .show();


            } else {
                // No explanation needed, we can request the permission.
                ActivityCompat.requestPermissions(this,
                        new String[]{Manifest.permission.ACCESS_FINE_LOCATION},
                        MY_PERMISSIONS_REQUEST_LOCATION);
            }
            return false;
        } else {
            return true;
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode,
                                           String permissions[], int[] grantResults) {
        switch (requestCode) {
            case MY_PERMISSIONS_REQUEST_LOCATION: {
                // If request is cancelled, the result arrays are empty.
                if (grantResults.length > 0
                        && grantResults[0] == PackageManager.PERMISSION_GRANTED) {

                    // permission was granted, yay! Do the
                    // location-related task you need to do.
                    if (ContextCompat.checkSelfPermission(this,
                            Manifest.permission.ACCESS_FINE_LOCATION)
                            == PackageManager.PERMISSION_GRANTED) {

                        //Request location updates
                    }

                } else {

                    // permission denied, boo! Disable the
                    // functionality that depends on this permission.

                }
                return;
            }

        }
    }`

I hope it helps. :)

**Comment by LevelMaxBR** [comment]
Thank you friend !
I'll try this solution, but anyway, thanks for the help.
