### ISSUE TITLE
Support for paging?

### ISSUE THREAD

**Issue by mirszy** [delight-im/Android-AdvancedWebView#177]
Does the AdvancedWebView support content paging? What I mean by this is - the content is divided into pages of webview's height (no vertical scrolling), one can switch between pages by some gesture (swipe left/right, top/bottom etc.).

If no, do you know any other modified webview which support something like this? (iOS webview supports it, so it's doable)

**Comment by ocram** [comment]
No, with regards to both questions. Sorry! Have actually never seen WebViews on Android doing such paging instead of continuous vertical scrolling.
