### ISSUE TITLE
right mouse click issue

### ISSUE THREAD

**Issue by ubergeekzone** [delight-im/Android-AdvancedWebView#178]
i have a remote webpage i am loading that allows for context menus to be shown on right click, currently they work if i do a left long click + right click. I am looking to make them work on long right click. 

I know in android the right click acts as a back button, i have disabled the back button in my webview. 

Is there a way to make the back work as a long left click?

**Comment by ocram** [comment]
Sorry, don’t know anything about this, and it seems this is not specific to this library.
