### ISSUE TITLE
JavaScript alert can not load in webView for android L Devices

### ISSUE THREAD

**Issue by androidvsourz** [delight-im/Android-AdvancedWebView#18]
Data is loaded from iFrame to android application, there is javascript dialog in iFrame for some task. all working fine in all other devices excluding Android Lollipop devices.

JavaScript Alert is not working in above api 20 in this webview.

Can you please help to show javascript dialog in Android Api >19 ?

Logcat Says "Cannot create a dialog, the WebView context is not an Activity"

**Comment by mwaclawek** [comment]
Thanks for your feedback!

This has indeed been a recent bug in the [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) app. You can read the official [bug report](https://code.google.com/p/chromium/issues/detail?id=478204) and fix this by updating that app to the latest version on your device.
