### ISSUE TITLE
Get video url

### ISSUE THREAD

**Issue by mudi256** [delight-im/Android-AdvancedWebView#181]
mwebview.getOriginalUrl ()
 is working if video open in new page, In case of Instagram video , playing same page, how can we get URL of instagram videos.

**Comment by ocram** [comment]
You could try the callbacks `onLoadResource` or `shouldInterceptRequest` from `WebViewClient`. These should trigger when the video loads, which may not be before you start playback. Other than that, I don’t think there’s anything built-in that you can use.

**Comment by mudi256** [comment]
it no working , please gave me an example
