### ISSUE TITLE
Scaling Image to fit the screen

### ISSUE THREAD

**Issue by Debashis-Sinha** [delight-im/Android-AdvancedWebView#182]
Image is not showing at full width of the WebView, it has blank space all around (like if you open a little iamge in your desktop browser). Any solution ?

**Comment by ocram** [comment]
First, you should check whether the blank space is actually outside of the `WebView` or inside of it. You could do this by loading a website with colored background and see if there’s also blank space around the site.

If it’s outside, adjust your layout to specify correct layout widths, heights, margins and paddings. Additionally, you may try

```java
myWebview.setScrollBarStyle(View.SCROLLBARS_OUTSIDE_OVERLAY);
```

to make sure the scroll bar is not causing the blank space.

If it’s inside, the following two methods (with proper values) might be the only thing you can do:

```java
myWebView.setInitialScale(50);
// or
myWebView.zoomBy(50.0f);
```
