### ISSUE TITLE
Upload button dosn’t work!

### ISSUE THREAD

**Issue by nifoea4** [delight-im/Android-AdvancedWebView#188]
I convert my site to an app with android studio, but i have a problem with upload button in the form, it dosn’t work although it works in my site so would anyone please help me with this problem

**Comment by ocram** [comment]
Without more details, nobody will be able to help.

Apart from that, see https://github.com/delight-im/Android-AdvancedWebView/issues/112 and https://github.com/delight-im/Android-AdvancedWebView/issues/39.
