### ISSUE TITLE
Mic cont be accessed mic and webcam not work

### ISSUE THREAD

**Issue by naguchennai** [delight-im/Android-AdvancedWebView#189]
`https://chatroom.tamil2friends.com/chat.php`

Mic and web cam not work we added all permisions

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />

Mic and webcam not work with webview..
it work fine with chrome tabs or crome

**Comment by LevelMaxBR** [comment]
UP!
I need this solution too, help us!
