### ISSUE TITLE
Done button for softkeyboard

### ISSUE THREAD

**Issue by Ashonko** [delight-im/Android-AdvancedWebView#190]
In one of the html pages, I have a number type input field `<input name="age" id="age" type="number">` . Is it possible to get a <kbd>Done</kbd> button instead of <kbd>⏎</kbd> button that hides/closes the keyboard when pressed?

**Comment by ocram** [comment]
As far as we know, this is entirely up to the [System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) implementation and you as a developer have no control over this, unless you can achieve this with different HTML markup.
