### ISSUE TITLE
Can't workout how to upload a file using POST

### ISSUE THREAD

**Issue by ukscone** [delight-im/Android-AdvancedWebView#191]
Hi,
i'm probably being very dense here but I can't workout how to upload a specific known file using POST. I have a simple PHP script on the server side that just takes an uploaded file and moves it to a directory and i don't want to use a form as the file chooser pops up on the phone and I only want my user to upload a specific zip file not any old file on their system. but i can't find anyway to do it although i am guessing it's something really simple that i'm missing

thanks

**Comment by ocram** [comment]
If you know the file and also the exact storage path, which appears to be the case, you could load the file in your application code on Android, perhaps encode it using Base64, and then send it to your server.

In general, what you’re trying to do here is not what the WebView has primarily been designed for. And, anyway, it’s not specific to this library.

The WebView has been designed to let a web page do what it can do in, say, your desktop browser. There, a web page cannot pick a specific file directly from your hard drive and upload it, either. It’s designed to give all power to the user and let *them* decide what to upload, if anything at all.

What you can do, however, is filter the accepted files by MIME types.
