### ISSUE TITLE
How to make Android webview remember username and password ?

### ISSUE THREAD

**Issue by jishnurajm** [delight-im/Android-AdvancedWebView#201]

**Comment by ocram** [comment]
```java
AdvancedWebView myWebView;
// ...
myWebView.getSettings().setSavePassword(true);
```

However, this method [is deprecated](https://developer.android.com/reference/android/webkit/WebSettings#setSavePassword(boolean)) and will apparently be removed without any replacement in a future version. So there won’t be any standard way left to do this.
