### ISSUE TITLE
Handle Blob URLs in Webview

### ISSUE THREAD

**Issue by utkarshns** [delight-im/Android-AdvancedWebView#203]
Saw this with no solution:
Issue #150 

@ocram 
I want to handle Blobs, files which have been created in browser.
I am using alasql and jsPDF.

Any insights from your end would be helpful.

**Comment by ocram** [comment]
Let’s keep the discussion in the other issue

**Comment by tsquaredesigns** [comment]
> Saw this with no solution:
> Issue #150
> 
> @ocram
> I want to handle Blobs, files which have been created in browser.
> I am using alasql and jsPDF.
> 
> Any insights from your end would be helpful.

Hey have you got the solution can you please help me out?
