### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by nb312** [delight-im/Android-AdvancedWebView#204]
I use the ```  api 'com.github.delight-im:Android-AdvancedWebView:v3.0.0' ``` 
It have this error 
```
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.delight-im:Android-AdvancedWebView:v3.0.0.
```

**Comment by ocram** [comment]
The lines shown in the README should work fine. Make sure you did indeed add the repository to the root file. If you still experience problems, please report back here.
