### ISSUE TITLE
About bottom input box in WebView is blocked by soft keyboard.

### ISSUE THREAD

**Issue by liyujiang-gzu** [delight-im/Android-AdvancedWebView#208]
This is actually a BUG of the Android system itself.([Issue 5497 - android -WebView adjustResize windowSoftInputMode breaks when activity is fullscreen - Android Open Source Project - Issue Tracker - Google Project Hosting](https://code.google.com/p/android/issues/detail?id=5497)).   
![image](https://user-images.githubusercontent.com/16816717/44967391-932b7a00-af73-11e8-895b-227f9c10dbd2.png)
Solution(https://stackoverflow.com/questions/7417123/android-how-to-adjust-layout-in-full-screen-mode-when-softkeyboard-is-visible/19494006#19494006):
```java
    static class AndroidBug5497Workaround {

        public static void assistActivity(Activity activity) {
            FrameLayout content = (FrameLayout) activity.findViewById(android.R.id.content);
            View childOfContent = content.getChildAt(0);
            childOfContent.setFitsSystemWindows(true);
            activity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
        }

    }
```

**Comment by ocram** [comment]
Thanks!

As you said, it’s a bug in the Android OS itself again, and the workaround cannot be implemented in this library either. Instead, it can easily be implemented in your own application code.

But it’s good to have this here for reference.
