### ISSUE TITLE
My app crash after adding Android-AdvancedWebView!!

### ISSUE THREAD

**Issue by zaxf** [delight-im/Android-AdvancedWebView#21]
Hello, My app started crashing after adding Android-AdvancedWebView,  I tried everything that I know  but, still!!?
I did everything in README.md but no lock..

**Comment by zaxf** [comment]
This is my MainActivity.java:
package com.rteet.www;

import android.content.Intent;
import android.graphics.Bitmap;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
//import com.rteet.www.AdvancedWebView;
import android.annotation.SuppressLint;



public class MainActivity extends ActionBarActivity {
    private AdvancedWebView mWebView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mWebView = (AdvancedWebView) findViewById(R.id.webview);
        //mWebView.setListener(this, this);
        mWebView.loadUrl("http://www.example.org/");

        // ...
    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @SuppressLint("NewApi")
    @Override
    protected void onResume() {
        super.onResume();
        mWebView.onResume();
        // ...
    }

    @SuppressLint("NewApi")
    @Override
    protected void onPause() {
        mWebView.onPause();
        // ...
        super.onPause();
    }

    @Override
    protected void onDestroy() {
        mWebView.onDestroy();
        // ...
        super.onDestroy();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent intent) {
        super.onActivityResult(requestCode, resultCode, intent);
        mWebView.onActivityResult(requestCode, resultCode, intent);
        // ...
    }

    @Override
    public void onBackPressed() {
        if (!mWebView.onBackPressed()) { return; }
        // ...
        super.onBackPressed();
    }

    //@Override
    public void onPageStarted(String url, Bitmap favicon) { }

    //@Override
    public void onPageFinished(String url) { }

    //@Override
    public void onPageError(int errorCode, String description, String failingUrl) { }

    //@Override
    public void onDownloadRequested(String url, String userAgent, String contentDisposition, String mimetype, long contentLength) { }

    //@Override
    public void onExternalPageRequest(String url) { }
}

**Comment by zaxf** [comment]
And the Activity_Main.xml:

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
    android:layout_height="match_parent" android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin" tools:context=".MainActivity">

    <im.delight.android.webview.AdvancedWebView
        android:id="@+id/webview"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</RelativeLayout>

**Comment by zaxf** [comment]
AndroidManifest.xml:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.rteet.www" >

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

**Comment by mwaclawek** [comment]
Sorry for the late reply!

Thanks for all the code snippets and the description of the problem. But in order to help you, we really need the exception that occurs and the stack trace that is shown for this exception.

 * Android Studio
   * http://stackoverflow.com/questions/16817566/logcat-is-gone-on-android-studio
   * https://developer.android.com/tools/debugging/debugging-studio.html
 * Eclipse
   * http://stackoverflow.com/questions/3280051/how-to-enable-logcat-console-in-eclipse-for-android

When your app crashes, it should produce a stack trace in the console that [looks like this](http://stackoverflow.com/questions/7841232/java-android-how-to-print-out-a-full-stack-trace). That output would help us detect the problem with your setup or code.

Thank you!
