### ISSUE TITLE
File not uploading ...

### ISSUE THREAD

**Issue by ARSujonx** [delight-im/Android-AdvancedWebView#211]
**Everything is in screenshot.** 
**url** = https://www2.cbox.ws/box/?boxid=2404343&boxtag=AjxNHs
**Device**: Android 5.1.1, API 22

file uploading from any browser normally. but using your webview i can select the file but nothing uploading or happening :( 

![a05](https://user-images.githubusercontent.com/37956905/45815553-df5c1580-bcfa-11e8-8e6f-52afc7472357.JPG)
![a02](https://user-images.githubusercontent.com/37956905/45815560-e08d4280-bcfa-11e8-92db-53e524294d5c.JPG)
![a01](https://user-images.githubusercontent.com/37956905/45815561-e08d4280-bcfa-11e8-8197-a33478fba639.JPG)

![a04](https://user-images.githubusercontent.com/37956905/45815554-dff4ac00-bcfa-11e8-9e51-20f0e2cc0151.JPG)
![a03](https://user-images.githubusercontent.com/37956905/45815557-dff4ac00-bcfa-11e8-9ed5-2e17fec3b453.JPG)

**i tested in both :**
compile 'com.github.delight-im:Android-AdvancedWebView:v3.1.3'
compile 'com.github.delight-im:Android-AdvancedWebView:v3.0.0'

**Comment by ocram** [comment]
It seems you didn’t implement all the `Activity` methods described in the README, such as `onActivityResult`.

**Comment by ARSujonx** [comment]
> It seems you didn’t implement all the `Activity` methods described in the README, such as `onActivityResult`.

Thanks. It's Working Perfectly  👍 👍 👍
