### ISSUE TITLE
onDownloadRequested()

### ISSUE THREAD

**Issue by sanefc23** [delight-im/Android-AdvancedWebView#215]
Hi! I really don't know how to use the onDownloadRequested method.

I'm trying to download a .png file. At first I managed to make it work, but it downloaded a url, not a .png. Could you help me with an example of how it works?

Sorry, I'm just getting started with Java and this library came in very handy with the project that i'm working on.

Thanks!

**Comment by sanefc23** [comment]
Hi! I really don't know how to use the onDownloadRequested method.

I'm trying to download a .png file. At first I managed to make it work, but it downloaded a url, not a .png. Could you help me with an example of how it works?

Sorry, I'm just getting started with Java and this library came in very handy with the project that i'm working on.

Thanks!

**Comment by ocram** [comment]
A complete example is in the README:

```java
@Override
public void onDownloadRequested(String url, String suggestedFilename, String mimeType, long contentLength, String contentDisposition, String userAgent) {
	// some file is available for download
	// either handle the download yourself or use the code below

	if (AdvancedWebView.handleDownload(this, url, suggestedFilename)) {
	    // download successfully handled
	}
	else {
	    // download couldn't be handled because user has disabled download manager app on the device
	    // TODO show some notice to the user
	}
}
```

Did you implement it like that? Still something going wrong?

**Comment by sanefc23** [comment]
Well it worked now, but when I download the file, it's a url, when it's supposed to be a .png.
