### ISSUE TITLE
where is onConsoleMessage?

### ISSUE THREAD

**Issue by rickyManalo** [delight-im/Android-AdvancedWebView#219]
Do I still use WebChromeClient or is it already included on the webview?

**Comment by ocram** [comment]
As usual, you should be able to call `setWebChromeClient` on the `AdvancedWebView` instance, provide your instance of `WebChromeClient`, and implement `onConsoleMessage` as desired.

Any problems with that?

**Comment by rickyManalo** [comment]
I thought it's part of the listeners as well. I have an app that use onConsoleMessage a lot. Thanks.

**Comment by ocram** [comment]
There is no separate listener or callback because we only added these for the most popular and most commonly used events. But regarding performance or functionality, there is no difference.
