### ISSUE TITLE
isHostnameAllowed doesnt check that the url string is non null

### ISSUE THREAD

**Issue by r2DoesInc** [delight-im/Android-AdvancedWebView#224]
Adding a null check will prevent this from crashing

**Comment by ocram** [comment]
Thanks!

Are you sure it can internally be called with `null`? Where? From `shouldOverrideUrlLoading`? Did you experience this?

As for the public API, i.e. the method being available for you to call, it’s not documented that you should actually pass `null` or that it behaves well in those situations.

There are tons of other methods and constructors in the popular APIs that you shouldn’t or must not pass `null` to. Perhaps a `NullPointerException` would be the most helpful and reasonable response that the method could generate.

**Comment by r2DoesInc** [comment]
Yes, its being called from `shouldOverrideUrlLoading`. I do not know the reason for the null value as it only is happening for a few users and the urls are hardcoded values, but it should be easy enough prevent the crash by simply checking the url value and stopping the load. I can handle this myself by subclassing the webview, but that seems like a lot of work for a simple null check.

**Comment by r2DoesInc** [comment]
```Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
im.delight.android.webview.AdvancedWebView.isHostnameAllowed ```

Yes, I am sure.

Yes, we have our list of permitted hostnames.

That would be a perfectly fine solution. We could simply show an error if we needed to, at least its better than a crash. Right now I dont have a way to catch the exception so the entire app fails when this occurs.

**Comment by ocram** [comment]
Just one last thing:

Since your error message displays the old method name, i.e. `isHostnameAllowed`, can you look up which version you are using? It’s probably not `v3.1.3`, which is the latest one.

Perhaps the problem can be solved by simply updating to a newer version of this library.

Otherwise, it would be perfect if we could get a line number for the crash.

**Comment by r2DoesInc** [comment]
It is an older version, I updated it when I noticed, but i am highly doubtful that this would have changed the issue. The line its crashing on is 

`final String actualHost = Uri.parse(url).getHost();`

Cant parse a null url string.

**Comment by ocram** [comment]
I get all that, but I think it’s indeed a different issue that would be fixed through an update. Let me quickly explain why:

Although you just said that it crashes on the parsing, in the previous comment you cited the error message as:

> Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

That makes sense, and it’s something that we had but didn’t have anymore.

In the past, we would [compare the host of the URL using `equals`](https://github.com/delight-im/Android-AdvancedWebView/blob/e347b203b0b89498d7fb72099e21240ecbb3f11f/Source/library/src/main/java/im/delight/android/webview/AdvancedWebView.java#L1082), but the host could certainly be `null` (e.g. on a file URI), which we didn’t check for.

So it really makes sense that it would crash in the past. But it doesn’t make sense that it would still crash now. The parsing can only crash if you really pass `null`, and I don’t see how the WebView’s URL may ever be null.
