### ISSUE TITLE
website in http does not work

### ISSUE THREAD

**Issue by LevelMaxBR** [delight-im/Android-AdvancedWebView#227]
Hello my colleagues, unfortunately when placing the url of my website (http://meusite.com) it gives an error and goes to the error page (index.html).

How can I fix this?
Sorry for my English.

**Comment by ocram** [comment]
Did you follow the README? Integrate the code correctly? Have an active internet connection on the device?

Displaying a site via HTTP is the most basic task possible and surely something that others would have noticed if it didn’t work here.

**Comment by ocram** [comment]
Ah, you’ve found it already. Was that because you’re on Android 9?

**Comment by ocram** [comment]
While this is not specific to this library, it’s probably a good idea to document this behavior in the README. So this [has been done](https://github.com/delight-im/Android-AdvancedWebView/commit/92381715773978904504d3a6ada6fb088d2cb859) now. Thanks!
