### ISSUE TITLE
Upload pictures from camera

### ISSUE THREAD

**Issue by marwis95** [delight-im/Android-AdvancedWebView#232]
Hi.
I have a little problem with using AdvancedWebView.
When i click the "upload file" on some webpage is calling "choose file dialog box" like this.
![not_ok](https://user-images.githubusercontent.com/26043077/53837871-f8e4d700-3f93-11e9-9a0a-c40cbe7123b7.png)

But i want to call "choose action" dialog box as it is for example in google chrome webbrowser.
I really need to call camera intent, take photo, ane upload it to my website.
![ok](https://user-images.githubusercontent.com/26043077/53837969-39445500-3f94-11e9-9a64-0f365faa2047.png)

Please help

**Comment by ocram** [comment]
See https://github.com/delight-im/Android-AdvancedWebView/issues/10, https://github.com/delight-im/Android-AdvancedWebView/issues/16, https://github.com/delight-im/Android-AdvancedWebView/issues/20 and https://github.com/delight-im/Android-AdvancedWebView/issues/81
