### ISSUE TITLE
image alignment Issue with large screen phones

### ISSUE THREAD

**Issue by josephmiller2000** [delight-im/Android-AdvancedWebView#233]
Check the attached screenshot, there is a issue with alignment for more than 6 inch screens.

But no issues in small screens devices.

![Snap_Shot_00506](https://user-images.githubusercontent.com/24210340/54274510-48d42700-45ae-11e9-953e-aa934f2752d0.jpg)

Embedded webview link : https://chatroom.tamil2friends.com/chat.php

**Comment by ocram** [comment]
What do you see on Chrome on the same device?

**Comment by josephmiller2000** [comment]
it works fine and there is no alignment issue in chrome view :)  Just the webview does this issue.

**Comment by ocram** [comment]
What Android version is it?

What happens if you build a minimal example with Android’s original `WebView` and as little custom code as necessary?

**Comment by josephmiller2000** [comment]
Its android version : 9

in default webview, it does the same issue, thats why i used your lib, advanced webview to fix it. But still it does the same.

**Comment by ocram** [comment]
In that case we probably can’t do anything about this, sorry.

If Android’s underlying WebView implementation renders this incorrectly, this is out of our control.

The strange thing is that it apparently renders correctly in Chrome on the same device.

The best solution may be trying to change your CSS.
