### ISSUE TITLE
Remove toast message which show on onPageStarted/onPageFinished

### ISSUE THREAD

**Issue by hunny12993** [delight-im/Android-AdvancedWebView#236]
Is there any way to hide the toast message which display on onPageFinished()/onPageStarted() method?

**Comment by ocram** [comment]
Well, sure!

If you don’t *explicitly* create and show `Toast` messages, they won’t show up.

You may have copied the source code from the included [sample application](https://github.com/delight-im/Android-AdvancedWebView/blob/master/Source/sample/), which contains five calls to `Toast.makeText` – which you can easily remove.
