### ISSUE TITLE
How to prevent webview reloading when switching fragment

### ISSUE THREAD

**Issue by chaocharleswang** [delight-im/Android-AdvancedWebView#242]
How to prevent webview reloading when switching fragment?

**Comment by ocram** [comment]
Your `WebView` instance is located inside of the `Fragment` and thus bound to the life cycle of the `Fragment`?

Can you try `Fragment#setRetainInstance` with a value of `true`?

If you are using `ViewPager`, you could also try `ViewPager#setOffscreenPageLimit` with a value as high as you need, e.g. `2`.
