### ISSUE TITLE
Dailymotion video page not shown after rotation

### ISSUE THREAD

**Issue by chaocharleswang** [delight-im/Android-AdvancedWebView#244]
I applied the following configs onto my activity to prevent webview reloading after rotation:

android:configChanges="keyboardHidden|orientation|screenSize">

It works well for most of the web pages. However, I found dailymotion video pages are not shown after the rotation, e.g., 
"https://www.dailymotion.com/video/x5pauql?playlist=x6ed6k"

How can I fix it?

**Comment by ocram** [comment]
It’s probably unrelated to this library and happens with the original `WebView` as well, so there’s not much we can do, unfortunately.
