### ISSUE TITLE
An error occurred while building the application.

### ISSUE THREAD

**Issue by php-id** [delight-im/Android-AdvancedWebView#246]
----------
1. ERROR in /storage/emulated/0/ApkBuilder/hello/src/com/example/hello/AdvancedWebView.java (at line 695)
	mCustomWebViewClient.onUnhandledInputEvent(view, event);
	                     ^^^^^^^^^^^^^^^^^^^^^
The method onUnhandledInputEvent(WebView, InputEvent) is undefined for the type WebViewClient
----------
2. ERROR in /storage/emulated/0/ApkBuilder/hello/src/com/example/hello/AdvancedWebView.java (at line 698)
	super.onUnhandledInputEvent(view, event);
	      ^^^^^^^^^^^^^^^^^^^^^
The method onUnhandledInputEvent(WebView, InputEvent) is undefined for the type WebViewClient
----------
2 problems (2 errors)

My Android version: 6.0

**Comment by ocram** [comment]
See https://github.com/delight-im/Android-AdvancedWebView/issues/83
