### ISSUE TITLE
Can we disable audio programatically? 

### ISSUE THREAD

**Issue by hardikJoshi123** [delight-im/Android-AdvancedWebView#247]
Hi,
 
 thanks for this awesome library. 

 I am facing 1 difficulty, currently I am playing sound cloud iFrame player within this webview. My requirement is I want to disable the sound whenever user click on a native button. Can we do that? 

 Looking forward for your help. 

 Thank you.!!!

**Comment by ocram** [comment]
You can either (temporarily) mute your whole Android app (that contains the WebView) or try to make JavaScript calls from the Android app through the WebView to the web page to change the volume. Other than that, I don’t think there’s anything you can do, specifically not muting the WebView in particular while keeping the sound of the Android app.
