### ISSUE TITLE
[Request] - Expose WebViewClient and WebChromeClient

### ISSUE THREAD

**Issue by krpot** [delight-im/Android-AdvancedWebView#250]

**Comment by krpot** [comment]
When I look at the source code, I think I can just implement my own classes and pass it to AdvancedWebView. Default implementation doesn't do anything actually.

**Comment by ocram** [comment]
This library has explicitly been designed so that you can use `setWebViewClient` and `setWebChromeClient` as usual, if that is what you were thinking about.
