### ISSUE TITLE
Google Play Console requests targetSdkVersion 28. My project stop showing web pages.

### ISSUE THREAD

**Issue by RabaHub** [delight-im/Android-AdvancedWebView#253]
Hi, this is my first post on GitHub so please forgive me If I'm doing it wrong.

Google Play Console is requesting a targetSdkVersion 28 for future pubblications. I tryed to update my project but the component stop showing web pages. If I set targetSdkVersion 26 everyting works normally.

Anyone is in the same situation?

**Comment by RabaHub** [comment]
This problem is solved adding

```
<application
    ....
    android:usesCleartextTraffic="true"
    ....>
```

in the manifest file.

**Comment by RabaHub** [comment]
more info at

[https://stackoverflow.com/questions/58118671/advancedwebview-delight-im-android-advancedwebview-stops-showing-web-pages-if/60246563#60246563](https://stackoverflow.com/questions/58118671/advancedwebview-delight-im-android-advancedwebview-stops-showing-web-pages-if/60246563#60246563)

**Comment by ocram** [comment]
Thank you!

This has also been documented in the README:

https://github.com/delight-im/Android-AdvancedWebView#cleartext-non-https-traffic

But I agree that it’s easy to miss.
