### ISSUE TITLE
How to use shouldOverrideUrlLoading

### ISSUE THREAD

**Issue by jinbatsu** [delight-im/Android-AdvancedWebView#26]
I want to check URL param (internal URL), if contains some "string", then do not load url, and display an Alert.

And for external URL, how to implement to go to default client Browser.

Thank You

**Comment by mwaclawek** [comment]
This should work just like the normal `WebView` implementation. So please refer to the docs for that method:

 * http://developer.android.com/reference/android/webkit/WebViewClient.html
 * http://stackoverflow.com/questions/26651586/difference-between-shouldoverrideurlloading-and-shouldinterceptrequest

Does that help?
