### ISSUE TITLE
Fails in file uploading

### ISSUE THREAD

**Issue by moylir** [delight-im/Android-AdvancedWebView#262]
I'm using an <input type="file"/> in my code and, although the navigator for selecting the files is opened, if I choose a file it ignores the selection and navigator is just opened once per app execution.

This is my complete <input type="file"/> in case it helps:

<input type="file" font-family: monospace; id="inputFileToLoad" align="center" accept=".jpg,.jpeg,.png" onchange="read(this);" width="48"/>

**Comment by tegarkurniawan** [comment]
same issue

**Comment by hichemkanon** [comment]
same issue me too

**Comment by ocram** [comment]
Thanks!

I guess the `font-family: monospace;` in the original post doesn’t actually belong there, right?

What about some absolutely basic `<input type="file" id="avatar" name="avatar">` without extra attributes such as `accept` or `onchange`? Can you reproduce the same problems with that syntax?

And what Android versions are you experiencing these problems on?

**Comment by mhemon** [comment]
the same problem, my app open gallery app once selected an image it's close nothing selected in the browser and open chooser at once per execution. I check the link with chrome browser it works fine only problem in my app browser.

**Comment by ocram** [comment]
Please see the newer https://github.com/delight-im/Android-AdvancedWebView/issues/285 now
