### ISSUE TITLE
How to choose the photo from the camera?

### ISSUE THREAD

**Issue by lorenzomalferrari** [delight-im/Android-AdvancedWebView#264]
We were testing your library to find a solution to our problem.

We have created a fake application in which we open Google Images in order to search for an image.

`mWebView.loadUrl("https://www.google.it/imghp?hl=it");`

We had to enable the descktop option to have the Camera button

`private static final String DESKTOP_USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36";`

` WebSettings webSettings = mWebView.getSettings();
        webSettings.setUserAgentString(DESKTOP_USER_AGENT);
        webSettings.setJavaScriptEnabled(true);`

Now we can select the icon and choose the item "Upload an image"

Select the "Choose file" button which only allows you to choose a photo from the phone.

It would be nice to be able to choose the photo even using the camera. What do you think about it?

**Comment by vikskod** [comment]
Hi, Did you get the solution?

**Comment by RawPlutonium** [comment]
Hello. I'm looking for this as well. Can anybody Help?
@ocram ?

**Comment by ocram** [comment]
Unfortunately, this hasn’t been implemented yet, and you’d have to add this on top of this library yourself.

See also https://github.com/delight-im/Android-AdvancedWebView/issues/81 and https://github.com/delight-im/Android-AdvancedWebView/issues/16 and https://github.com/delight-im/Android-AdvancedWebView/issues/20 and https://github.com/delight-im/Android-AdvancedWebView/issues/10 and https://github.com/delight-im/Android-AdvancedWebView/issues/43 and https://github.com/delight-im/Android-AdvancedWebView/issues/48 and https://github.com/delight-im/Android-AdvancedWebView/issues/116 and https://github.com/delight-im/Android-AdvancedWebView/issues/137 and https://github.com/delight-im/Android-AdvancedWebView/issues/210 and https://github.com/delight-im/Android-AdvancedWebView/issues/232 and https://github.com/delight-im/Android-AdvancedWebView/issues/248 . Let’s track this there.
