### ISSUE TITLE
Webviews with URL that requires camera access don't work with AdvancedWebView

### ISSUE THREAD

**Issue by amanzan** [delight-im/Android-AdvancedWebView#274]
I'm testing a simple Webview with this URL: https://qrcodescan.in/ and it does not work with AdvancedWebView
This URL requires camera access, and it does so in a normal WebView. 
AdvancedWebView does not even prompt user to allow camera access: it shows an "Unable to access the camera" message. 
Is there any way to make this work?

**Comment by ocram** [comment]
Thanks!

Did that site really work *better* in the original WebView, out of the box, than with this library?

Did you find the cause of this problem?
