### ISSUE TITLE
Fatal Error - App Crash Log

### ISSUE THREAD

**Issue by BlameTheNetwork** [delight-im/Android-AdvancedWebView#28]
Receiving fatal error when accessing just the fragment that the AdvancedWebView should be on... I have AdvancedWebView.java source in it's own file. Not using the main java onCall, just another fragment to display the AdvancedWebView.  Any ideas? The Line 26 it mentions is the rootView = inflater.inflate.... etc etc. line.

Here's the error:
``` 
: FATAL EXCEPTION: main
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime: Process: com.test.app, PID: 27247
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime: android.view.InflateException: Binary XML file line #6: Error inflating class im.delight.android.webview.AdvancedWebView
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at com.test.app.report2_Fragment.onCreateView(report2_Fragment.java:26)

Caused by: java.lang.ClassNotFoundException: Didn't find class "im.delight.android.webview.AdvancedWebView" on path: DexPathList[[zip file "/data/app/com.test.app-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:578)
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at com.test.app.report2_Fragment.onCreateView(report2_Fragment.java:26) 
10-18 16:43:36.821 27247-27247/com.test.app E/AndroidRuntime:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962) 
```

Here's the fragment:
```
package com.test.app;

import android.annotation.SuppressLint;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;



public class report2_Fragment extends Fragment implements AdvancedWebView.Listener {

    private AdvancedWebView mWebView;

    public report2_Fragment() { }
    View rootView;
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        rootView = inflater.inflate(R.layout.report2, container, false);

        mWebView = (AdvancedWebView) rootView.findViewById(R.id.webview);
        mWebView.setListener(getActivity(), this);
        mWebView.loadUrl("http://www.example.org/");

        // ...

        return rootView;
    }

    @SuppressLint("NewApi")
    @Override
    public void onResume() {
        super.onResume();
        mWebView.onResume();
        // ...
    }

    @SuppressLint("NewApi")
    @Override
    public void onPause() {
        mWebView.onPause();
        // ...
        super.onPause();
    }

    @Override
    public void onDestroy() {
        mWebView.onDestroy();
        // ...
        super.onDestroy();
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent intent) {
        super.onActivityResult(requestCode, resultCode, intent);
        mWebView.onActivityResult(requestCode, resultCode, intent);
        // ...
    }

    @Override
    public void onPageStarted(String url, Bitmap favicon) { }

    @Override
    public void onPageFinished(String url) { }

    @Override
    public void onPageError(int errorCode, String description, String failingUrl) { }

    @Override
    public void onDownloadRequested(String url, String userAgent, String contentDisposition, String mimetype, long contentLength) { }

    @Override
    public void onExternalPageRequest(String url) { }

}
```

**Comment by BlameTheNetwork** [comment]
Also here's my report2.xml... no changes from your code:

```<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="match_parent"
    android:id="@+id/container">

    <im.delight.android.webview.AdvancedWebView
        android:id="@+id/webview"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</RelativeLayout>
```

**Comment by mwaclawek** [comment]
Thanks for your question!

The error message says:
`Didn't find class "im.delight.android.webview.AdvancedWebView"`

So it seems you have the `AdvancedWebView` class in your `com.test.app` package as well.

Please try either including our JAR instead of copying the source file or creating a package named `im.delight.android.webview` in your own source code and moving the class there.

Can you try this?

**Comment by BlameTheNetwork** [comment]
So when I include the .jar in my libs directory, and I can see the project structure already includes all *.jar's in lib as dependencies, I immediately get an error in the fragment at "implements AdvancedWebView.Listener".  It's like it doesn't know about that .jar file to see the classes/methods. Sorry, I'm a bit new to this Android thing, I don't mean to waste your time.

**Comment by BlameTheNetwork** [comment]
Disregard, it was my mistake. For anyone else new like myself, and this is already documented I just wasn't getting it....
1. Save the .jar file (I placed it in my projects lib directory)
2. Right click on your app, select New > Module
3. On the pop up screen, select "Import .JAR/.AAR Package". Click Next.
4. Select the .JAR file for AdvancedWebView. Click Finish.
5. Complete.

Then the native classes and methods will be recognized in Android Studio in your other java files within the project.

Thanks for the assistance!

**Comment by BlameTheNetwork** [comment]
One last question then... this solution still requires additional code added by myself in order to successfully upload files?  I see the upload prompt works, but after selecting an image nothing further occurs. Is this permissions related, or due to additional code being required on top of the base classes provided?

**Comment by mwaclawek** [comment]
No problem!

Thanks for documenting this (regarding Android Studio) for everyone who may have the same problem.

Turning to the file uploads: If you followed the guide in the README, everything should work automatically. Please check if you included all method calls and callbacks.

 * From the permissions, you only need internet access, as documented
 * Check if you have the `mWebView.setListener(...)` line
 * Check if you have the `onActivityResult(...)` method and call, paying special attention to the issues that come with `Fragment` instances here (see README and other issues)
 * You can check if your device is supported (by Android, not by this library) via `AdvancedWebView.isFileUploadAvailable()`
 * If the upload prompt closes, what happens? What are you expecting? The file should be available to the website then, either for async upload immediately (via AJAX) or via normal upload after posting the form

Does that help?

**Comment by BlameTheNetwork** [comment]
I'll take a look and you can close this out if you'd like as it's likely my fault.  The prompt opens allowing choice of an image. After selecting one, it closes however the websites do not act as though they received a file. I cannot afterwards open the upload button again at that point, but completing the submission doesn't send an image. I've tried a few websites and had the same results. I'll look into the fragment issues.

I have the code mentioned:

```
mWebView.setListener(getActivity(), this);
```

```
public void onActivityResult(int requestCode, int resultCode, Intent intent) {
        super.onActivityResult(requestCode, resultCode, intent);
        mWebView.onActivityResult(requestCode, resultCode, intent);
        // ...
    }
```

phone is a GalaxyS6, I think it should be good.

**Comment by BlameTheNetwork** [comment]
Oh, regarding that additional code to pass data from the Fragment code, I get an error about mFragment cannot be resolved. Should this already be defined? Or can it not use it because this isn't the main and is a fragment instead?

**Comment by mwaclawek** [comment]
This is really what you need to do and why it's not working for you, yet:
https://github.com/delight-im/Android-AdvancedWebView/tree/a876e0fc2aa8a6912aea68ceaa7afe962802db07#with-fragments-from-the-support-library-androidsupportv4appfragment

So you need to override `onActivityResult(...)` *both* in the `Fragment` *and* in the `FragmentActivity`, as shown in those docs.

Well, it seems you tried all that already. So the only thing you need to fix is that you cannot leave out the `if (mFragment != null) { ... }` part.

It's expected that `mFragment` is not defined. This is a variable (class member) that you have to define in your own code (in your `FragmentActivity`).

It must point to the `Fragment` that contains the `AdvancedWebView`, i.e. the instance of `report2_Fragment`, which is usually the current or active `Fragment`.

You have these instances in your `Activity` already. You need them because otherwise you cannot show them. So just track which is the currently shown `Fragment` instance (put it into `mFragment`) and you're done.

You can also get the current `Fragment` like this, perhaps:
http://developer.android.com/training/basics/fragments/communicating.html#Deliver

Otherwise, maybe you'll want to try an `Activity` *without* a `Fragment` or use the standard `Fragment` classes, not the ones from the support package. If you use the standard ones (your app will work on API levels 11+ only), you can refer to the other part of the setup guide, which is easier.
