### ISSUE TITLE
Ads removers

### ISSUE THREAD

**Issue by havefun77612** [delight-im/Android-AdvancedWebView#281]
I suggest adding feature of block ads banner on opened websites

**Comment by ocram** [comment]
Not going to happen, sorry.

You can’t just implement the huge complexity of something like [uBlock Origin](https://github.com/gorhill/uBlock), plus the filter lists, as some additional feature in a library.

For specific sites, you may try to implement this yourself, building on top of this library, perhaps even just in the application code (without needing to touch the library itself).
