### ISSUE TITLE
video element live stream

### ISSUE THREAD

**Issue by abdullahozcan** [delight-im/Android-AdvancedWebView#282]
I want to use video element with  live stream for webinar software how can I set manifesto for this?

**Comment by dphans** [comment]
What technology do you apply to use? Did you checked with webrtc supported?
For example, go to https://test.webrtc.org in both chrome and your webview in devices (of course, enable needed permissions for webrtc work properly).

**Comment by ocram** [comment]
Thanks, @dphans!

Good point, as using that link probably is the easiest way to debug (and develop) this.

**Comment by abdullahozcan** [comment]
Thanks for answers @dphans
