### ISSUE TITLE
com.example

### ISSUE THREAD

**Issue by PenguinOfTheSky** [delight-im/Android-AdvancedWebView#290]
... forbidden on google play to have com.example app. Tried changing the name, then whole project stopped working with a dozen errors. Maybe name it something else? Not really plug and play at the moment.

**Comment by ocram** [comment]
Thanks!

> forbidden on google play to have com.example app

Not sure which part you have been trying to publish.

> Tried changing the name, then whole project stopped working with a dozen errors.

Where did you try to change the name? This project here consists of the library (`Source/library/build.gradle`) and a small sample application (`Source/sample/build.gradle`). Neither would result in a `com.example` application.

> Not really plug and play at the moment.

It’s not meant to be plug-and-play in the sense that you can just paste one URL, compile the project and upload it to an app store. If this is what you’re looking for, this project here is not what you want. Right here, you have a *library*, which you can easily use (“plug-and-play”) in your application. But you need (a little) Android development experience.
