### ISSUE TITLE
File Download

### ISSUE THREAD

**Issue by rijudewan** [delight-im/Android-AdvancedWebView#33]
file download is not working for me  when i click download button nothing happens ... file upload works  great

**Comment by mwaclawek** [comment]
Thanks for your feedback!

Can you give a link to the site with the download button? Or an excerpt of the HTML code that includes the download button?

**Comment by rijudewan** [comment]
http://merosath.com
this  site use clipbucket video sharing script ... each video had download button .. but when click on download nothing happens ..

**Comment by mwaclawek** [comment]
The HTML source for the download link is as follows:

`<a role="menuitem" tabindex="-1" href="...mp4" download=""><span class="glyphicon glyphicon-download-alt"></span>...</a>`

As explained [here](https://github.com/delight-im/Android-AdvancedWebView/issues/31), links with the `download` attribute don't work.

If you can remove that attribute (e.g. via JavaScript), it will probably work, however.
