### ISSUE TITLE
Android 4.4.2 with Input type=file

### ISSUE THREAD

**Issue by kirpheaice** [delight-im/Android-AdvancedWebView#36]
Greeting, 
This AdvancedWebView seems cannot work on Android 4.4.2(ASUS ZenFone and BlueStack Simulator) with html input type=file ? I tried From 4.1(API 16) to 6.0(API 23) with Emluator or HTC devices. But Android 4.4 has no response as I press the INPUT TYPE=FILE , on <openFileChooser> function. 

您好，請問一下，它是不是在Android 4.4.2 (ASUS ZenFone and BlueStack Simulator) 時，在上傳檔案這的功能，會無法正常運作？我試了4.1(Emluator,API 16) , 4.2.2(HTC one SV, API 17), 4.3(Emluator , API 18) , 5.0(Emluator,API 21) ,5.1(HTC One M7, API 22) , 6.0(HTC One M8,API 23) , 它們都可以正常回應 INPUT TYPE=FILE的openFileChooser，但是API 19的4.4沒有反應…

**Comment by mwaclawek** [comment]
This is a bug in Android. It has been discussed [here](https://github.com/delight-im/Android-AdvancedWebView/issues/4) already.

In order to check if file uploads are available or not, you can just check the result of `AdvancedWebView.isFileUploadAvailable()`.
