### ISSUE TITLE
File chooser not working on versions 4.4.1 and 4.4.2

### ISSUE THREAD

**Issue by dayerdl** [delight-im/Android-AdvancedWebView#37]
Having this html:

input type="submit" value="upload file" 

The button does not open the Filechooser. Is there any work around this problem?

**Comment by mwaclawek** [comment]
Thanks!

This has been discussed quite a few times already, see https://github.com/delight-im/Android-AdvancedWebView/issues/4

Unfortunately, there is no workaround as this is a bug in the Android OS itself. Sorry!

The only solution is waiting for users to upgrade to 5.0, 5.1, 6.0 etc.

**Comment by wadleo** [comment]
Hey guys, maybe you guys can try to implement the solution provided in the link below, thanks.
https://github.com/henrychuangtw/Kitkat-WebView

**Comment by mwaclawek** [comment]
@wadleo That's not really a solution. It requires you to change the server-side code as well. You can just add this to your app even if you're using this library.
