### ISSUE TITLE
Multiple file upload?

### ISSUE THREAD

**Issue by tinyCoder32** [delight-im/Android-AdvancedWebView#40]
Hello, thanks for the great job.

How can I enable multiple file select?
My HTML input element has the multiple attribute set, but it is only allowing one file to be selected!

any advice please?

**Comment by mwaclawek** [comment]
Thanks for your question!

Please check the following pull request by @james2001:

https://github.com/delight-im/Android-AdvancedWebView/pull/23/files

Does this help? Can you implement it (after copying this library's JAVA file to your app and removing the JAR)?

**Comment by rijudewan** [comment]
hi
thank you it works great .. i was wondering if it possible to set cache like when user lunch the main activity load data from cache

**Comment by mwaclawek** [comment]
@rijudewan You might want to take a look at the `WebSettings#setCacheMode` method. But please open separate issues for your questions that aren't related to existing issues. Thank you!

**Comment by praveshagrawal** [comment]
It didn't worked for me, i replaced with your above code, but still able to select only one image at a time.
How may it get done!

**Comment by praveshagrawal** [comment]
Done!
Thanks

**Comment by mwaclawek** [comment]
Feature has been implemented, see https://github.com/delight-im/Android-AdvancedWebView/pull/23
