### ISSUE TITLE
iFrame URL click issue

### ISSUE THREAD

**Issue by gopal-yadav** [delight-im/Android-AdvancedWebView#41]
Hi there

Thanks for the great webview.  While using this webview, we are facing an issue with external link URLs inside iFrame. In our case, there are multiple iframes on a webpage www.unlockar.com/horoscope. When one clicks on the link 'Read the article on astrocenter.com' the target url opens up in the same iframe. While opening this link in chrome, it opens up the target url in another tab.

I want to sort this issue out by bringing a new webview with target url in front of user.

**Comment by mwaclawek** [comment]
Thanks for your question!

The `WebView` can't just open a new window without your help. This is because the `WebView` does only display *one* single website at a time and does not have tabs. In addition to that, it can't open a new window because that requires starting another instance of your `Activity` or at least adding another `WebView` instance.

What you have to set is the following option:

```java
myWebView.getSettings().setSupportMultipleWindows(true);
// myWebView.getSettings().setJavaScriptCanOpenWindowsAutomatically(true);
```

After that, you only have to implement the following method in your `WebChromeClient`:

```java
boolean onCreateWindow(WebView view, boolean isDialog, boolean isUserGesture, Message resultMsg)
```

You have to set your `WebChromeClient` on the `WebView` like this, if you haven't already done this:

```java
myWebView.setWebChromeClient(new WebChromeClient() { });
```

Note sure about the contents of that `onCreateWindow` method, though. You may try something like this, but this hasn't been tested yet:

```java
WebView newWebView = new WebView(MyActivity.this);
// rootLayout.addView(newWebView);
WebView.WebViewTransport transport = (WebView.WebViewTransport) resultMsg.obj;
transport.setWebView(newWebView);
resultMsg.sendToTarget();

return true;
```

But what you could certainly do is checking if the `onCreateWindow` is called at all, by inserting a log statement in its first line.

Is this of any help to you?

**Comment by gopal-yadav** [comment]
Thanks a lot! solved my problem

**Comment by mwaclawek** [comment]
@gopal-yadav Thanks for your feedback! Can you please comment on what was the exact code snippet that you needed? Did you have to apply any changes to the solution I suggested?

How does it work now? Does it open another `AdvancedWebView` instance, similar to opening another window or tab?

Thank you!

**Comment by gopal-yadav** [comment]
Hi there, here is the code snippet that I used to make it work. I had to change it a little bit as per my particular use case. Yes, it is opening another instance of AdvancedWebView now.

 webView.getSettings().setJavaScriptEnabled(true);
				webView.getSettings().setSupportMultipleWindows(true);
				webView.getSettings().setJavaScriptCanOpenWindowsAutomatically(true);
				webView.getSettings().setAppCacheEnabled(true);
		        webView.getSettings().setBuiltInZoomControls(true);
		        webView.getSettings().setSaveFormData(true);
	      		
				 mWebChromeClient = new myWebChromeClient();				
				 webView.setWebChromeClient(mWebChromeClient);
				
				webView.loadUrl(urltoOpen);
				
				
				
				
				
				
				
				
		private class myWebChromeClient extends WebChromeClient {
		private View mVideoProgressView;

		@Override
		public boolean onCreateWindow(WebView view, boolean dialog, boolean userGesture, android.os.Message resultMsg) {

			AdvancedWebView webView = new AdvancedWebView(New_WebActivity.this);
			webView.setTag("aks_advwv_" + i);
			llp.addView(webView, LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);

			mWebViewClient = new myWebViewClient();
			webView.setWebViewClient(mWebViewClient);

			WebView.WebViewTransport transport = (WebView.WebViewTransport) resultMsg.obj;
			transport.setWebView(webView);
			resultMsg.sendToTarget();

			return true;
		}

		@Override
		public void onShowCustomView(View view, int requestedOrientation, CustomViewCallback callback) {
			onShowCustomView(view, callback);
		}

		@Override
		public void onShowCustomView(View view, CustomViewCallback callback) {

			if (mCustomView != null) {
				callback.onCustomViewHidden();
				return;
			}
			mCustomView = view;
			webView.setVisibility(View.GONE);
			customViewContainer.setVisibility(View.VISIBLE);
			customViewContainer.addView(view);
			customViewCallback = callback;
		}

		@Override
		public View getVideoLoadingProgressView() {

			if (mVideoProgressView == null) {
				LayoutInflater inflater = LayoutInflater.from(New_WebActivity.this);
				mVideoProgressView = inflater.inflate(R.layout.video_progress, null);
			}
			return mVideoProgressView;
		}

		@Override
		public void onHideCustomView() {
			super.onHideCustomView();
			if (mCustomView == null)
				return;

			webView.setVisibility(View.VISIBLE);
			customViewContainer.setVisibility(View.GONE);

			mCustomView.setVisibility(View.GONE);

			customViewContainer.removeView(mCustomView);
			customViewCallback.onCustomViewHidden();

			mCustomView = null;
		}
	}

**Comment by mwaclawek** [comment]
Thank you so much!

Instructions on how to enable multi-window support have now been added to the README: https://github.com/delight-im/Android-AdvancedWebView/commit/6f6759009b850661a69f6dfa57f238ffe9694456

**Comment by chamnap** [comment]
@ocram, I got this error message, `NewActivity is not an enclosing class`. How to fix this?

**Comment by ocram** [comment]
@chamnap Is `NewActivity` really the current `Activity` that you're calling this constructor in? I guess not. Try changing `NewActivity.this` to just `this` or replace `NewActivity` with the correct name.

Generally, please open a new, separate issue for new problems or questions :) Thanks!

**Comment by chamnap** [comment]
No, it's not the current `Activity`. I created a new `Activity`, and I called it `NewActivity`. Okay, I'll open a separate issue. I'm too newbie to android. Thanks :)
