### ISSUE TITLE
webview.addhttpheader issue

### ISSUE THREAD

**Issue by ukeypad** [delight-im/Android-AdvancedWebView#42]
hello,

i tested this AdvancedWebView.. it works nice
but i have a problem

when i addheader "X-Requested-With","somthing"
it add header works
but when url load resources like <css> or <javascript src=''> or <img src=''>
X-Requested-With header was "my.app.id"
how can i addheader for every requests and resource in requests?

**Comment by mwaclawek** [comment]
Thanks for your question!

This is indeed a bug in this library and has already been mentioned here: https://github.com/delight-im/Android-AdvancedWebView/issues/27

Closing this as a duplicate. Let's track our progress in the other issue thread :)
