### ISSUE TITLE
Camera option not coming on browse click button html file using Advanced-WebView android version 6

### ISSUE THREAD

**Issue by vatsrahul62** [delight-im/Android-AdvancedWebView#43]
Hi,

I tried to load a URL with the help of Android-AdvancedWebView. Works fine but when I click on browse button from the HTML Page there is no option coming to capture photo from camera and upload the same to page.

**Comment by mwaclawek** [comment]
Thanks for your question!

Can you please check if https://github.com/delight-im/Android-AdvancedWebView/issues/10 or https://github.com/delight-im/Android-AdvancedWebView/issues/16 or https://github.com/delight-im/Android-AdvancedWebView/issues/20 is helpful to you?

**Comment by tegarkurniawan** [comment]
how to solution ? the same issue, i already check #10 #16 #20 but not found solution
