### ISSUE TITLE
Custom hosts 

### ISSUE THREAD

**Issue by tikkat3** [delight-im/Android-AdvancedWebView#44]
url like :     custom://showImage?image=http://www.pic.com/pic1.jpeg&image=http://www.pic1.com/pic2.jpeg

i handle this in method  onPageStatr()

But when i return from the GalleryActivity，the webvie  show error page  :  can't not find custom://showImage?image=http://www.pic.com/pic1.jpeg&image=http://www.pic1.com/pic2.jpeg

how can i solve this problem ,please?

**Comment by tikkat3** [comment]
webview callback  this method  onPageError(int errorCode, String description, String failingUrl) 

the failingUrl is   custom://showImage?image=http://www.pic.com/pic1.jpeg&image=http://www.pic1.com/pic2.jpeg

but i how can i tell the webview i had handled this url ???

**Comment by mwaclawek** [comment]
Thanks for your feedback!

Can you please log the values for all three of `errorCode`, `description` and `failingUrl` from ` onPageError`? Thanks!

Why do you need the custom URL scheme at all? How do you load the page? How does the app transition to the gallery app? Can you show some more code excerpts?

Apart from that, can you please try if your custom URLs work with the original `WebView` from the Android SDK instead of the enhanced version from this library?

**Comment by tikkat3** [comment]
@mwaclawek  Helllo,man~ Thanks for your help
The issue have already been solved. i use the original WebView，the code 
`
        @Override
        public boolean shouldOverrideUrlLoading(WebView view, final String url) {

            if (url.startsWith("custom://")) {
                // This is my web site, so do not override; let my WebView load the page
                if(mAdvanceListener!=null){
                    mAdvanceListener.onExternalPageRequest(url);
                }
                if(mWebView!=null){
                    mWebView.stopLoading();
                }
                return false;
            }else{
                view.loadUrl(url);
                return true;
            }
            //  return super.shouldOverrideUrlLoading(view, url);
        }`
**why do you need the custom URL scheme at all? **
Because Server has a communicate protocol with Client 

 **How do you load the page?**
Please see the code

**How does the app transition to the gallery app?**
I am sorry that I didn't say it clearly. When the user clicks on the picture on the HTML，WebView will call the method "shouldOverrideUrlLoading(WebView view, final String ur)"  the url like custom://showImage?image=http://www.pic.com/pic1.jpeg&image=http://www.pic1.com/pic2.jpeg
I analysis the url ，get the image's address and  show in GalleryActivity(For browsing pictures)

**Comment by mwaclawek** [comment]
@tikkat3 Thanks for letting us now!

> The issue have already been solved. i use the original WebView

Glad that it's working now. But does it work with this library, i.e. the `AdvancedWebView` class, or only with the original `WebView` class? Which component do you have in your layout?

**Comment by tikkat3** [comment]
@mwaclawek use original WebView class ， I suggest that ,AdvancedWebView add a method addScheme(String scheme) to handle custom url . We know that the structure of URI is  **scheme://host:port/path**   Thank you once again
