### ISSUE TITLE
Screen goes white when click on youtube's fullscreen button

### ISSUE THREAD

**Issue by haneetGH** [delight-im/Android-AdvancedWebView#45]
hello

Firstly thank you for creating this. Actually i'm using your lib in making a web view based app in which some youtube video should play. videos are playing but when i click on full screen mode the screen goes white but audio still stream 
![screenshot_2016-03-30-02-33-46](https://cloud.githubusercontent.com/assets/8691909/14123916/5deb05ea-f620-11e5-8f31-ed93560b8717.png)
![screenshot_2016-03-30-02-33-52](https://cloud.githubusercontent.com/assets/8691909/14123917/5e66dada-f620-11e5-953a-02ceb2b73807.png)

**Comment by mwaclawek** [comment]
Thanks for your report!

Can you please try if the same problem occurs with the original `WebView` from the Android SDK instead of the enhanced version from this library?

And what happens if you go to `youtube.com` itself and try the fullscreen mode there?

**Comment by haneetGH** [comment]
Thanks for replying actually there's was a problem from my side now everything is working fine just have to add chromeclient and some there bit of code 

Regards 

Haneet singh

**Comment by mwaclawek** [comment]
@haneetGH Thanks, glad it works :)
