### ISSUE TITLE
input file upload not working on android 4.4.X

### ISSUE THREAD

**Issue by summa123** [delight-im/Android-AdvancedWebView#46]
Hi Author,
Really it is great tool to over come all issues with default webview. i am having one problem. i have webpage which has file input. i am loading this webpage into your webview. it is working fine in other version. but in android 4.4, it is not showing filechooser. how to fix this issue please guide me.

**Comment by mwaclawek** [comment]
Please see https://github.com/delight-im/Android-AdvancedWebView/issues/4 and https://github.com/delight-im/Android-AdvancedWebView/issues/11 and https://github.com/delight-im/Android-AdvancedWebView/issues/14

Thanks!
