### ISSUE TITLE
How to send a photo just shotted?

### ISSUE THREAD

**Issue by rignaneseleo** [delight-im/Android-AdvancedWebView#48]
If I want upload a photo, the chooser is opened but I can't find the option 'shot a photo'. Is there? :)

**Comment by mwaclawek** [comment]
Thanks for your question!

Does https://github.com/delight-im/Android-AdvancedWebView/issues/43 or https://github.com/delight-im/Android-AdvancedWebView/issues/20 or https://github.com/delight-im/Android-AdvancedWebView/issues/16 or https://github.com/delight-im/Android-AdvancedWebView/issues/10 help?
