### ISSUE TITLE
I cannot build a Signed APK

### ISSUE THREAD

**Issue by rignaneseleo** [delight-im/Android-AdvancedWebView#49]
Hi! Thanks for your work!
I would add your webview to my project (SlimSocial for Facebook).
I have added all and all works but I can only do the debug on my telephone because when I try to build an APK I have:
```
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Can't write [C:\Users\Leo\Source\Repos\SlimFacebook\SlimFacebook - alpha\app\build\intermediates\transforms\proguard\release\jars\3\1f\main.jar] (Can't read [C:\Users\Leo\Source\Repos\SlimFacebook\SlimFacebook - alpha\app\build\intermediates\classes\release(;;;;;;**/*.class)] (Duplicate zip entry [im/delight/android/webview/a.class == im/delight/android/webview/AdvancedWebView$1.class]))
```

My gradle code:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

My app gradle code:
```
apply plugin: 'com.android.application'
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "it.rignanese.leo.slimfacebook"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 29
        versionName "2.2.4 APLPHA"
    }
    buildTypes {
        debug {
            minifyEnabled true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            zipAlignEnabled true
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        disable 'MissingTranslation'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.github.delight-im:Android-AdvancedWebView:v2.1.0'
    compile 'com.android.support:appcompat-v7:23.1.0'
}
```
On my proguard-rules.pro
```
-keep class * extends android.webkit.WebChromeClient { *; }
-dontwarn im.delight.android.webview.**
```

How can I solve this? Maybe there is incompatibility but I cannot find it :\ 
Thanks

**Comment by mwaclawek** [comment]
Thanks!

 1. Do you have a duplicate of the `AdvancedWebView` class in your own source code, perhaps?
 2. Can you disable ProGuard (obfuscation) temporarily and try again, please?

**Comment by rignaneseleo** [comment]
I look for duplicate but I don't find anything.
In my proguard I've added 
```
-dontshrink
-dontoptimize
```
but I still receive
`Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Can't write [C:\Users\rigna\Desktop\Progetti\Android\SlimFacebook - alpha\app\build\intermediates\transforms\proguard\release\jars\3\1f\main.jar] (Can't read [C:\Users\rigna\Desktop\Progetti\Android\SlimFacebook - alpha\app\build\intermediates\classes\release(;;;;;;**/*.class)] (Duplicate zip entry [im/delight/android/webview/a.class == im/delight/android/webview/AdvancedWebView$1.class]))`

Maybe it's a gradle bug..

ps. I've tried to build apk on a different pc and it doesn't work.

**Comment by mwaclawek** [comment]
Thanks!

Feel free to remove `-dontshrink` and `-dontoptimize` from your ProGuard configuration again.

What I was referring to was changing the `minifyEnabled` in your `build.gradle` as follows:

```
buildTypes {
	debug {
		minifyEnabled false
		proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
	}
	release {
		zipAlignEnabled true
		minifyEnabled false
		shrinkResources true
		proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
		proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
	}
}
```

Can you try this? If that still doesn't work, what about `zipAlignEnabled false` (and `shrinkResources false`) as well, temporarily?

And did you check this?

> Do you have a duplicate of the `AdvancedWebView` class in your own source code, perhaps?

Maybe you copied the package and class to your own source code before, then included the library via Gradle, now you have it twice.

**Comment by rignaneseleo** [comment]
With some tests I received:
`multiple dex files`
and
`signing config externaloverride`

HOW I SOLVED:
I've removed all AdvancedWebView.class in my project folder (there was one into a renamed folder) and I've moved my keys to another folder.
Now it works. 
Thanks for this class and for the support !

**Comment by mwaclawek** [comment]
@rignaneseleo Thank you :)

**Comment by d-rahul** [comment]
This issue is coming due to pro-guard enable in the release config of the app. So the solution is either remove pro-guard or put the indicated code snippet as in the link https://readyandroid.wordpress.com/errorexecution-failed-for-task-apptransformclassesandresourceswithproguardforrelease/

**Comment by aliassad** [comment]
Add These Dex option
dexOptions {
        preDexLibraries = false
        javaMaxHeapSize "2g" //4g
    }
