### ISSUE TITLE
Not found method shouldInterceptRequest

### ISSUE THREAD

**Issue by joielechong** [delight-im/Android-AdvancedWebView#51]
I try using _shouldInterceptRequest_ method by extending WebViewClient with below class:
`private class MyWebViewClient extends WebViewClient{
    @Override public WebResourceResponse shouldInterceptRequest(WebView view, String url) {
      Log.d("shouldInterceptRequest", "url: " + url);
      return super.shouldInterceptRequest(view, url);
   }
}`

And set it to AdvancedWebView with below code:
`mWebView.setWebViewClient(new MyWebViewClient());`

But when I'm start loading the webpage, nothing happens in _shouldInterceptRequest_.

And I found error "could not found method shouldInterceptRequest" in debug window.

But using generic WebView _shouldInterceptRequest_ is called.

**Comment by mwaclawek** [comment]
Thank you!

What Android version or API level is the device or emulator that you're testing this on?

Any chance you're using ...

```java
WebResourceResponse shouldInterceptRequest(WebView view, String url)
```

... with the default `WebView` and ...

```java
WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request)
```

... with this library?

**Comment by joielechong** [comment]
Sorry for my late response.
I use device with ICS 4.0.3 (API 15)
It turns out that I will get `shouldInterceptRequest` working by enabling setAllowFileAccess with the following code:
 ```
WebSettings settings = webView.getSettings();
  // enable shouldInterceptRequest in ICS device
  // but never tested on other device.
  settings.setAllowFileAccess(true);
```

For pre-lollipop device I use:
`WebResourceResponse shouldInterceptRequest(WebView view, String url)`
and for lollipop and past-lollipop:
`WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request)`
