### ISSUE TITLE
There is no Get Header method.

### ISSUE THREAD

**Issue by demonsantosh** [delight-im/Android-AdvancedWebView#53]
I'm trying to get header response on web view but in AdvancedWebVIew this feature is not included. Can you add this feature?

**Comment by mwaclawek** [comment]
Thanks for your feature request!

Do you want to access HTTP headers that you previously added via `addHttpHeader`? If so, we could add that, of course.

Or do you want to access the HTTP headers sent by the server and received by your `WebView`? If so, I don't think that's possible :( We would probably have to perform all the requests ourselves and take that task away from the `WebView`.
