### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Minhaj-ali** [delight-im/Android-AdvancedWebView#54]
it loads my page but after some seconds it automatically redirects to some other pages which does not belonged to my website.. plz help

**Comment by mwaclawek** [comment]
Thanks for your report!

I don't think this is related to this library and can only imagine that it's caused by some code on your website. Can you give a link to the specific page of your website that you're loading?

Do you have this problem with other websites as well?

**Comment by Minhaj-ali** [comment]
http://www.organicjesus.com/ thanks for respose this is the link of website and yes it is doing the same things with other webs

**Comment by mwaclawek** [comment]
Thanks! I'm afraid I can't see any reason why there should be any redirect.

Can anyone reproduce this?

Can you share the relevant excerpts from your code? How did you use this library and how did you load the website?

If you load `https://github.com/` instead, are you redirected as well? To what page?

**Comment by Minhaj-ali** [comment]
if i am using popular sites like facebook, youtube than it won't redirect but when i use other sites it redirects but well i have solved the problem when i add this code everything works fine

`mWebView.setWebViewClient(new WebViewClient(){

            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                if (Uri.parse(url).getHost().contains("www.organicjesus.com")) {
                    // This is my web site, so do not override; let my WebView load the page
                    //   http://dev-team.campustrading.co.nz/

                   view.loadUrl(url);
                    return false;
                }
                // Otherwise, the link is not for a page on my site, so launch another Activity that handles URLs
               // Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
               // startActivity(intent);
                return true;
            }
        });`
