### ISSUE TITLE
How to override some methods of your WebChromeClient?

### ISSUE THREAD

**Issue by rignaneseleo** [delight-im/Android-AdvancedWebView#56]
I have to override **onShowCustomView** and **onHideCustomView**.
Maybe it's a stupid question but I don't how can I do :\

Thanks!

**Comment by mwaclawek** [comment]
```java
myWebView.setWebChromeClient(new WebChromeClient() {
    // your overridden methods go here
});
```

Does that work?

**Comment by rignaneseleo** [comment]
In this way I think to create a new WebChromeClient, losing all your WebChromeClient improvements

**Comment by mwaclawek** [comment]
Can you try it? It should just preserve everything so that nothing is actually lost.
