### ISSUE TITLE
cache is not working

### ISSUE THREAD

**Issue by rijudewan** [delight-im/Android-AdvancedWebView#57]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            Window window = getWindow();
            window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            window.setStatusBarColor(Color.parseColor("#D32F2F"));

        }
        progressBar = (ProgressBar) findViewById(R.id.progressBar);
        mWebView = (AdvancedWebView) findViewById(R.id.webview);
        //Ads View
        AdView mAdView = (AdView) findViewById(R.id.adView);
        AdRequest adRequest = new AdRequest.Builder().build();
        mAdView.loadAd(adRequest);

        if (savedInstanceState != null) {
            mWebView.restoreState(savedInstanceState);

        }
        else{
            webSettings=mWebView.getSettings();
            mWebView.setListener(this, this);
            mWebView.setGeolocationEnabled(false);
            mWebView.setMixedContentAllowed(true);
            mWebView.setCookiesEnabled(true);
            mWebView.getSettings().setAppCachePath(getApplicationContext().getCacheDir().getAbsolutePath());
            mWebView.getSettings().setAllowFileAccess(true);
            mWebView.getSettings().setAppCacheEnabled(true);
            mWebView.setThirdPartyCookiesEnabled(true);
            mWebView.getSettings().setCacheMode(webSettings.LOAD_DEFAULT);
            if ( !isNetworkAvailable() ) { // loading offline
                mWebView.getSettings().setCacheMode( WebSettings.LOAD_CACHE_ELSE_NETWORK );
                AlertDialog.Builder builder = new AlertDialog.Builder(context);
                builder.setMessage("Sorry ! There Is No Internet Connection! Please Enable Your Internet Connection");
                builder.setCancelable(false);
                builder.setPositiveButton("OK",
                        new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int id) {
                                dialog.cancel();
                                //context.finish();
                            }
                        });
                builder.show();
                //Toast.makeText(MainActivity.this, "No Internet Connection", Toast.LENGTH_SHORT).show();
            }
            mWebView.setWebViewClient(new WebViewClient() {
                @Override
                public boolean shouldOverrideUrlLoading(WebView view, String url) {
                    progressBar.setVisibility(View.VISIBLE);
                    view.loadUrl(url);
                    return true;
                }

                @Override
                public void onPageFinished(WebView view, String url) {
                    //Toast.makeText(MainActivity.this, "Finished loading", Toast.LENGTH_SHORT).show();
                }

            });
            mWebView.setWebChromeClient(new WebChromeClient() {

                @Override
                public void onReceivedTitle(WebView view, String title) {
                    super.onReceivedTitle(view, title);
                    Toast.makeText(MainActivity.this, title, Toast.LENGTH_SHORT).show();
                }

            });

            mWebView.addHttpHeader("X-Requested-With", "");
            mWebView.loadUrl(TEST_PAGE_URL);

        }

**Comment by mwaclawek** [comment]
1. Change `mWebView.getSettings().setCacheMode(webSettings.LOAD_DEFAULT);` to `mWebView.getSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);`
 1. Change `mWebView.getSettings().setCacheMode( WebSettings.LOAD_CACHE_ELSE_NETWORK );` to `mWebView.getSettings().setCacheMode(WebSettings.LOAD_CACHE_ONLY);`
 1. Check the value of `isNetworkAvailable()` with a log statement

Anyway, this is not related to this library here because it's using methods of the original `WebView` exclusively for caching.
