### ISSUE TITLE
image and video upload in the wrong orientation

### ISSUE THREAD

**Issue by LairdWalker** [delight-im/Android-AdvancedWebView#58]
when using this webview code if you upload and image or video it upload just fine but in the wrong orientation is there a way to correct this

**Comment by mwaclawek** [comment]
Unfortunately, I think there's everything correct with the `WebView`, with this library here, and also with your application.

The correct orientation is probably saved in the image's EXIF data only. It's a JPEG file, right?

That would mean you have to examine the EXIF data, check whether a rotation has been proposed or not, and apply it.
