### ISSUE TITLE
Readme example Listener missing closing );

### ISSUE THREAD

**Issue by jflamman** [delight-im/Android-AdvancedWebView#6]
mWebView.setListener(this, new AdvancedWebView.Listener() {
...
}

should be:

mWebView.setListener(this, new AdvancedWebView.Listener() {
...
});

**Comment by mwaclawek** [comment]
Of course! Fixed with https://github.com/delight-im/Android-AdvancedWebView/commit/850488869ad9b47826768852af2591fc129564f7

Thank you :)

**Comment by jflamman** [comment]
Great!
