### ISSUE TITLE
[Upload] FileChooser does not start in Android 4.3

### ISSUE THREAD

**Issue by TostF** [delight-im/Android-AdvancedWebView#60]
What I understand is that it does not work in 4.4.x versions. However it does not work on my Samsung G4 with Android 4.3. It does work on Android 6.0.1 (Samsung G7).

Any ideas what might not be working?

**Comment by mwaclawek** [comment]
Thanks for your report!

That's really strange. Problems on Android 4.3 are not known so far. Is `Build.VERSION.SDK_INT` really something *below* (on the G4) or *above* (on the G7) `19`?

Did you follow the README for the setup in your `Activity` or `Fragment`?

Maybe someone else can verify or disprove.

**Comment by TostF** [comment]
Yes I did follow README and set up all required methods for `Fragment`. It is working on G7 (23 API). On G4 its 18 API.

**Comment by mwaclawek** [comment]
Is there any other Android 4.3 device that you could test this on? Or the emulator?

**Comment by TostF** [comment]
I will test it out, on vacations atm ;)

**Comment by mwaclawek** [comment]
@TostF Any news? :)

**Comment by TostF** [comment]
Oh right I totally forgot about it >.< Vacations ect. will do the testing this weekend.
