### ISSUE TITLE
Do you have the code in the eclipse?

### ISSUE THREAD

**Issue by catjoker** [delight-im/Android-AdvancedWebView#62]
I want to use it with eclipse.Although I know that the Android studio is more popular than eclipse,I can't change your code to fit eclipse successfully. - -! I hope you can help me.
(Forgive my English is poor)

**Comment by mwaclawek** [comment]
Please try to move to Android Studio as well, at least for work on this library, if you want to debug it or work on it :)

This library itself has made the switch from Eclipse to Android Studio [very recently only](https://github.com/delight-im/Android-AdvancedWebView/commit/37d0c865312d189f6032de23d01fe34f96e2755d). Android Studio is really mature enough now (and Eclipse soon lacking support) to justify the switch.

Eclipse is not supported by this library anymore, sorry!
