### ISSUE TITLE
App crashing after loading some url

### ISSUE THREAD

**Issue by Minhaj-ali** [delight-im/Android-AdvancedWebView#64]
In starting webview is working fine but after loading some images app crashes

**Comment by mwaclawek** [comment]
Thanks for your report!

It's highly unlikely that this is indeed caused by this library. If the original `WebView` does not crash, neither should this library. Unless there's some mistake in your configuration or setup.

Apart from that, a few details regarding your code and the URLs would be helpful.

**Comment by Minhaj-ali** [comment]
package com.doctor.Solutionz;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.app.ProgressDialog;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.webkit.WebViewClient;

import com.google.android.gms.analytics.GoogleAnalytics;
import com.google.android.gms.analytics.HitBuilders;
import com.google.android.gms.analytics.Tracker;

import im.delight.android.webview.AdvancedWebView;

public class WebView extends Activity implements AdvancedWebView.Listener {

    private AdvancedWebView mWebView;
    ProgressDialog pd;
    String url_home = "http://doctorsolutionz.com/index.php/visitor";


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_web_view);

        Tracker t = ((GoogleAnalyticsApp)
getApplication()).getTracker(GoogleAnalyticsApp.TrackerName.APP_TRACKER);
        t.setScreenName("Main Activity");
        t.send(new HitBuilders.AppViewBuilder().build());
        pd = new ProgressDialog(this);
        pd.setMessage("Loading");


        mWebView = (AdvancedWebView) findViewById(R.id.webview);
        mWebView.setListener(this, this);
        mWebView.setMixedContentAllowed(true);
        mWebView.setCookiesEnabled(true);
        mWebView.loadUrl("http://doctorsolutionz.com/index.php/visitor");
        mWebView.getSettings().setSupportZoom(true);
        mWebView.getSettings().setBuiltInZoomControls(true);
        mWebView.getSettings().setCacheMode(mWebView.getSettings().LOAD_NO_CACHE);
        mWebView.clearCache(true);


        mWebView.setWebViewClient(new WebViewClient());
    }

    @SuppressLint("NewApi")
    @Override
    protected void onResume() {
        super.onResume();
        mWebView.onResume();
        // ...
    }

    @SuppressLint("NewApi")
    @Override
    protected void onPause() {
        mWebView.onPause();
        // ...
        super.onPause();
    }

    @Override
    protected void onDestroy() {
        mWebView.onDestroy();
        // ...
        super.onDestroy();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode,
Intent intent) {
        super.onActivityResult(requestCode, resultCode, intent);
        mWebView.onActivityResult(requestCode, resultCode, intent);
        // ...
    }

    @Override
    public void onBackPressed() {
        if (!mWebView.onBackPressed()) {
            mWebView.clearCache(true);

            return;

        }

        if (mWebView.getUrl().equals("http://192.168.1.2:8082/Doctors_New/index.php"))
{
            onDestroy();
        }
        // ...
        super.onBackPressed();
    }

    @Override
    public void onPageStarted(String url, Bitmap favicon) {
        mWebView.clearCache(true);

        pd.show();
    }

    @Override
    public void onPageFinished(String url) {
        pd.dismiss();
        mWebView.clearCache(true);
    }

    @Override
    public void onPageError(int errorCode, String description, String
failingUrl) {
    }

    @Override
    public void onDownloadRequested(String url, String userAgent,
String contentDisposition, String mimetype, long contentLength) {
    }

    @Override
    public void onExternalPageRequest(String url) {
    }

    @Override
    protected void onStart() {
        // TODO Auto-generated method stub
        super.onStart();
        GoogleAnalytics.getInstance(WebView.this).reportActivityStart(this);
    }

    @Override
    protected void onStop() {
        // TODO Auto-generated method stub
        super.onStop();
        GoogleAnalytics.getInstance(WebView.this).reportActivityStop(this);
    }


}

**Comment by Minhaj-ali** [comment]
package com.doctor.Solutionz;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.app.ProgressDialog;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.webkit.WebViewClient;

import com.google.android.gms.analytics.GoogleAnalytics;
import com.google.android.gms.analytics.HitBuilders;
import com.google.android.gms.analytics.Tracker;

import im.delight.android.webview.AdvancedWebView;

public class WebView extends Activity implements AdvancedWebView.Listener {

    private AdvancedWebView mWebView;
    ProgressDialog pd;
    String url_home = "http://doctorsolutionz.com/index.php/visitor";


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_web_view);

        Tracker t = ((GoogleAnalyticsApp) getApplication()).getTracker(GoogleAnalyticsApp.TrackerName.APP_TRACKER);
        t.setScreenName("Main Activity");
        t.send(new HitBuilders.AppViewBuilder().build());
        pd = new ProgressDialog(this);
        pd.setMessage("Loading");


        mWebView = (AdvancedWebView) findViewById(R.id.webview);
        mWebView.setListener(this, this);
        mWebView.setMixedContentAllowed(true);
        mWebView.setCookiesEnabled(true);
        mWebView.loadUrl("http://doctorsolutionz.com/index.php/visitor");
        mWebView.getSettings().setSupportZoom(true);
        mWebView.getSettings().setBuiltInZoomControls(true);
        mWebView.getSettings().setCacheMode(mWebView.getSettings().LOAD_NO_CACHE);
        mWebView.clearCache(true);


        mWebView.setWebViewClient(new WebViewClient());
    }

    @SuppressLint("NewApi")
    @Override
    protected void onResume() {
        super.onResume();
        mWebView.onResume();
        // ...
    }

    @SuppressLint("NewApi")
    @Override
    protected void onPause() {
        mWebView.onPause();
        // ...
        super.onPause();
    }

    @Override
    protected void onDestroy() {
        mWebView.onDestroy();
        // ...
        super.onDestroy();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent intent) {
        super.onActivityResult(requestCode, resultCode, intent);
        mWebView.onActivityResult(requestCode, resultCode, intent);
        // ...
    }

    @Override
    public void onBackPressed() {
        if (!mWebView.onBackPressed()) {
            mWebView.clearCache(true);

            return;

        }

        if (mWebView.getUrl().equals("http://192.168.1.2:8082/Doctors_New/index.php")) {
            onDestroy();
        }
        // ...
        super.onBackPressed();
    }

    @Override
    public void onPageStarted(String url, Bitmap favicon) {
        mWebView.clearCache(true);

        pd.show();
    }

    @Override
    public void onPageFinished(String url) {
        pd.dismiss();
        mWebView.clearCache(true);
    }

    @Override
    public void onPageError(int errorCode, String description, String failingUrl) {
    }

    @Override
    public void onDownloadRequested(String url, String userAgent, String contentDisposition, String mimetype, long contentLength) {
    }

    @Override
    public void onExternalPageRequest(String url) {
    }

    @Override
    protected void onStart() {
        // TODO Auto-generated method stub
        super.onStart();
        GoogleAnalytics.getInstance(WebView.this).reportActivityStart(this);
    }

    @Override
    protected void onStop() {
        // TODO Auto-generated method stub
        super.onStop();
        GoogleAnalytics.getInstance(WebView.this).reportActivityStop(this);
    }


}

**Comment by Minhaj-ali** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.doctor.Solutionz">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />


    <application
        android:name="com.doctor.Solutionz.GoogleAnalyticsApp"
        android:allowBackup="true"
        android:icon="@drawable/appicon"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:name="com.doctor.Solutionz.MainActivity"
            android:screenOrientation="portrait"></activity>
        <activity
            android:name="com.doctor.Solutionz.SplashScreen"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <receiver
            android:name="com.google.android.gms.analytics.AnalyticsReceiver"
            android:enabled="true">
            <intent-filter>
                <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.google.android.gms.analytics.AnalyticsService"
            android:enabled="true"
            android:exported="false" />

        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
        <meta-data
            android:name="com.google.android.gms.analytics.globalConfigResource"
            android:resource="@xml/global_tracker" />

        <activity
            android:name="com.doctor.Solutionz.WebView"
            android:screenOrientation="portrait"></activity>
    </application>

</manifest>

**Comment by Minhaj-ali** [comment]
this is my code and this is the url of my app
https://play.google.com/store/apps/details?id=com.smit16.dcpart2

kindly reply me if you find i am doing anything wrong because app is still crashing after loading some pages...

**Comment by mwaclawek** [comment]
If it's crashing, there must be an exception and an accompanying stack trace in your debug log. Please post that as well.
