### ISSUE TITLE
Using camera

### ISSUE THREAD

**Issue by catjoker** [delight-im/Android-AdvancedWebView#65]
I want to use the camera and gallery.But there is no camera button in the AlertDialog(it may be AlertDialog - -!).
I don't know whether it is my code's problem or not.
Thanks.
![i lj6rcb fu_p _d ns81hh](https://cloud.githubusercontent.com/assets/17564399/16574584/28949dfe-42b3-11e6-85f9-6714fdca8cdf.gif)

![screenshot_android](https://cloud.githubusercontent.com/assets/17564399/16573358/836a6384-42a5-11e6-9991-4804872d350b.png)

**Comment by icoolguy1995** [comment]
I also have the same issue. If i use default webview to upload images to webpage all works. But if change Webview to AdvancedWebView, file chooser directly open(No alert dialog), and when i select any images file chooser closes, and image does not upload.

**Comment by mwaclawek** [comment]
Thanks for your question!

This has already been discussed a few times. So maybe https://github.com/delight-im/Android-AdvancedWebView/issues/10 or https://github.com/delight-im/Android-AdvancedWebView/issues/20 are helpful to you.
