### ISSUE TITLE
How to load html data directly from string 

### ISSUE THREAD

**Issue by h4h13** [delight-im/Android-AdvancedWebView#68]
Can any one help me with loading html data from string with this library without URL if not available this feature can developer can add this 

forgive me with my English

**Comment by mwaclawek** [comment]
Please try this:

```java
myWebView.loadDataWithBaseURL(null, "<html>...</html>", "text/html", "utf-8", null);
```

Does it help?

**Comment by mwaclawek** [comment]
This solution has been confirmed to work.

The method `myWebView.loadHtml("<html>...</html>");` has been added as a shortcut in https://github.com/delight-im/Android-AdvancedWebView/commit/3f5ef184c655f114b6054fe5ba60987526c5a204
