### ISSUE TITLE
HUAWEI android 6.0 OS,webview,multiple

### ISSUE THREAD

**Issue by LeoZhengZzz** [delight-im/Android-AdvancedWebView#72]
i want to input multiple files by <input type="file" name="img" multiple="multiple" />.as you know,below 4.x is not support.My phone is HUAWEI android 6.0. It worked well in android browser,but my requirement  is  "multiple" can use in android webview.
This AdvancedWebView you write can solve my problem?
thx!

**Comment by LeoZhengZzz** [comment]
and my email is : zhengshl2012@163.com, wish your help.thx

**Comment by mwaclawek** [comment]
* Is the device really running on Android 5.0+?
 * Does your gallery or file manager app support multiple selections? Can you verify this with other apps that open a file picker?
 * Did you add the `multiple` attribute to your HTML source for the `<input type="file">` element?
