### ISSUE TITLE
Youtube videos aren't working in the webview

### ISSUE THREAD

**Issue by EgyptianM** [delight-im/Android-AdvancedWebView#73]
Hi ,
I have a forum and I built and app based on your awesome webview but I noticed that youtube videoes aren't working at all, no sound or video.

I tried the native webview it worked with sound only no video.

When I open Youtube.com in your webview it works fine.

What's the problem and how to solve.

You can try this link : 

https://androiders.club/index.php?threads/yrd-brmg-ttbiq-lmuqyk.12/

It contains a video.

Thank you.

**Comment by mwaclawek** [comment]
Thanks for your report!

If you open that same video on m.youtube.com by following the external link from the video player, it is working with this library? But on that site with the embedded player, it is *not* working?

**Comment by ArthurSav** [comment]
Same goes for vimeo. I get a blank screen when opening the webview but i can hear the sound

**Comment by ocram** [comment]
Thanks, @ArthurSav!

Can anybody with this problem please check the following for YouTube and/or Vimeo?

 * Embedded
   * Audio
     * [ ] Works with this library!
     * [ ] Works with the original WebView!
   * Video
     * [ ] Works with this library!
     * [ ] Works with the original WebView!
 * Fullscreen
   * Audio
     * [ ] Works with this library!
     * [ ] Works with the original WebView!
   * Video
     * [ ] Works with this library!
     * [ ] Works with the original WebView!

**Comment by ArthurSav** [comment]
I have both youtube & vimeo. Youtube is working great.

**Youtube**
- Embedded mode works with audio & video. 
- Haven't tried fullscreen.

**Vimeo**
- Haven't tried embedded.
- Fullscreen. When i press `play` the screen becomes white. Sounds works

I think vimeo is trying to go full screen and that's when the screen becomes white.

Haven't used the default webview, so i can't comment on that.

**Comment by sazid** [comment]
See #84 for full screen video support.

**Comment by ArthurSav** [comment]
@sazid Thanks, will give it a try and close the issue if tit works

**Comment by ocram** [comment]
@ArthurSav If the problems are really exclusive to fullscreen mode, the issue referenced by @sazid may indeed solve this. But from @EgyptianM's original comment, I understood that the problems would occur in embedded mode as well (which would be strange).
