### ISSUE TITLE
leaks memory,already override onResume,onPause,onDestory method

### ISSUE THREAD

**Issue by hzqjyyx** [delight-im/Android-AdvancedWebView#74]
I have used Android Studio's Monitor and Leakcany to find leak memory.
Monitor shows every time I leave the activity/fragment,it will remains, while the leakcany tells me "No leak found,The GC was being lazy".

**Here is the code**

```
@Override
    protected void onResume() {
        super.onResume();
        webView.onResume();
    }

    @Override
    protected void onPause() {
        webView.onPause();
        super.onPause();
    }

    @Override
    protected void onDestroy() {
        webView.onDestroy();
        super.onDestroy();
    }
```

**Comment by mwaclawek** [comment]
Thanks for investigating this!

Any news here? You should have the same problems with the original `WebView`. Can you check that?
