### ISSUE TITLE
‘accept’ No effect

### ISSUE THREAD

**Issue by yugai** [delight-im/Android-AdvancedWebView#76]
html input type="file" accept="image/*". Why is open file browser?

**Comment by mwaclawek** [comment]
Thanks!

Currently, we require the type for uploadable files to be set beforehand via [`setUploadableFileTypes`](https://github.com/delight-im/Android-AdvancedWebView/blob/ab994097de27c1aa3b85ffc0b220c8fd83a446fd/Source/library/src/main/java/im/delight/android/webview/AdvancedWebView.java#L184).

Does it work for you if you use that method to set the types?
