### ISSUE TITLE
File uploads not working out of the box

### ISSUE THREAD

**Issue by jflamman** [delight-im/Android-AdvancedWebView#8]
Are there any steps that need to be taken to enable file uploads?

The app is working (after a minor tweak of adding the Listener's static methods to Activity class itself instead of in mWebView.setListener and adding some code so external links would open) but clicking a file upload button triggers no action out of the box.

The page I use for testing has a regular file upload field. When I click the button in Chrome browser on my phone (or on my desktop) the file dialog box opens and I'm able to upload a file. When I click it inside the App, no luck.

The same testpage also has a fancy Bootstrap uploader (https://github.com/kartik-v/bootstrap-fileinput) - with same results.

**Comment by jflamman** [comment]
I just noticed a closed issue referring to this.. I have 4.4.2 - so I guess it's specific to my Android version?

**Comment by mwaclawek** [comment]
Yeah, you're right, this will not work on Android 4.4.2 and unfortunately cannot be fixed, either :(

The issue you referenced was probably this: https://github.com/delight-im/Android-AdvancedWebView/issues/4

Sorry! But you can test on other devices (or emulator) and see that it works.

**Comment by jflamman** [comment]
Will do, thanks!
