### ISSUE TITLE
How to do this ?

### ISSUE THREAD

**Issue by s1mar** [delight-im/Android-AdvancedWebView#80]
Can we get the mouse click or touch coordinates ?

and is it possible to load webpages stored in local file storage ?

**Comment by mwaclawek** [comment]
Thanks for your question!

Where do you want to do this?

In the HTML page that is being displayed in the view, using JavaScript code?

```js
$(document).on("touchstart", ".selector", function (e) {
	var touched = e.originalEvent.touches[0];
	// touched.pageX;
	// touched.pageY;
});
```

Or on the view itself, using Java code?

```java
myView.setOnTouchListener(new View.OnTouchListener() {
	@Override
	public boolean onTouch(View v, MotionEvent event) {
		// event.getX()
		// event.getY()
		return true;
	}
});
```

For separate questions, please open separate issues :) Thank you!
