### ISSUE TITLE
4.4.2 html file input

### ISSUE THREAD

**Issue by celilbey** [delight-im/Android-AdvancedWebView#82]
Only Android 4.4.2 Kitkat.
When I clicked in site input file button not shown filechooser

**Comment by zayn1991** [comment]
On 4.2.2 not works too

**Comment by ocram** [comment]
See https://github.com/delight-im/Android-AdvancedWebView/issues/4 for 4.4.2.

On 4.2.2, it should really work, however. Please try again, perhaps even on another device or using the emulator.
