### ISSUE TITLE
Fullscreen video not working

### ISSUE THREAD

**Issue by sazid** [delight-im/Android-AdvancedWebView#84]
Environment:
Android 7.0 - Nexus 5 (using Chrome WebView from Play Store)

Problem:
When full screen button is pressed on any video (youtube, animemobile.com or any site), the WebView becomes blank and white.

Expected:
The video should start playing in full screen mode (covering the whole screen hiding both the navigation and notification bar).

What works:
If I use this library: https://github.com/cprcrack/VideoEnabledWebView I can play videos in full screen without any problem at all.

**Comment by sazid** [comment]
Sorry about the issue. It seems the I needed to implement `onShowCustomView(...)` and `onHideCustomView(...)` in a custom WebChromeClient. If anyone need further reference, here's a helpful link: http://stackoverflow.com/a/16199649/1941132

**Comment by ocram** [comment]
@sazid No problem -- and thanks for posting your solution!

Had this been easier with the other library that you cited? That is, does that other library make fullscreen videos work by default, without you having to implement some additional methods? If so, we should probably make this easier as well, I guess.

**Comment by sazid** [comment]
The library I mentioned, simplifies a little bit of code but there's a limitation to it. It can load only 1 video per page. I think, documenting this process is a better option than trying to simplify it :)

Oh, one more thing. I'm using your library to build an open-source web browser. Here's the link: https://github.com/sazid/Browse
Do try it out (there's an apk in the release page). You can also mention it in your README if you want :D

**Comment by ocram** [comment]
Thanks a lot! Considering your clarification, we won't make any changes to the code for now and keep this issue here as a documentation for everyone who wants fullscreen video to work. Thank you!

**Comment by ocram** [comment]
Just to add more context here for others (coming from other issues):

You need to set a `WebChromeClient` with [`WebChromeClient#onShowCustomView(...)`](https://developer.android.com/reference/android/webkit/WebChromeClient#onShowCustomView(android.view.View,%20android.webkit.WebChromeClient.CustomViewCallback)) and [`WebChromeClient#onHideCustomView()`](https://developer.android.com/reference/android/webkit/WebChromeClient#onHideCustomView()), and a little logic around managing the `View` instances and using the callbacks. See https://stackoverflow.com/questions/15768837/playing-html5-video-on-fullscreen-in-android-webview
