### ISSUE TITLE
White page opening external link

### ISSUE THREAD

**Issue by rignaneseleo** [delight-im/Android-AdvancedWebView#86]
Hi, I am using your webview in my app https://github.com/rignaneseleo/SlimSocial-for-Facebook

When I open an external link, it opens the browser and when I go back, I see a white page.

Where is the issue?
Maybe there is something wrong in shouldOverrideUrlLoading method

**Comment by ocram** [comment]
Thanks for your report!

 * What exactly is "an external link" in terms of your app? How is decided which link is external and which is not?
 * Which browser is opened? Some browse installed on the user's device, other than your app, e.g. Firefox, Chrome or "Internet"?
 * Where do you go back to? To your app? And everything you see is a white screen? Or is the content of the website the only thing that's white while everything around is still there?
 * Did you call `AdvancedWebView#addPermittedHostname` somewhere in your app?
 * Did you implement `AdvancedWebView.Listener#onExternalPageRequest` in your app (with some code that actually *does* something)?
 * Did you call `AdvancedWebView#setWebViewClient` and implement `WebViewClient#shouldOverrideUrlLoading` somewhere in your app?
 * Has this problem been introduced recently? Did you make any other changes to your app?
 * Can you re-produce this problem reliably?
 * Is this problem restricted to certain Android versions or API levels?

**Comment by rignaneseleo** [comment]
Thanks for your reply.

1. In my app, an external link is all links not included in the domain facebook.com and its subdomain like m.facebook.com, touch.facebook.com
2. The bug exists with all browsers
3. When I go back from the browser to my app, I see the white screen
4. Yes, I allow the facebook hostname and in fact, external links are opened in browsers
5. Yes, I use startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(url)));
6. I use setWebChromeClient and I cannot find shouldOverrideUrlLoading method
7. From 2-3 versions, but I saw the code changed in my new release but it seems good
8. This bug appens every time I open an external link
9. I haven't tried but I think it there is in all versions

**Comment by ocram** [comment]
Thanks!

What happens if you just leave your app via the home button (as opposed to following an external link)? If you return to your app afterwards, either by launching it again or by choosing it from the list of recently opened apps, does the same problem occur?

What about your implementations of `onResume`, `onPause` and `onDestroy`? Do you have what the README suggests for those methods?

**Comment by rignaneseleo** [comment]
no, if I open my app after pressing the home button, all works.

Each time I press an external link, a white page is opened and AFTER a few second, the menu with the choose of the browser is opened. When I come back from the browser to app, I see the white page opened before.

You can try this bug downloading my app from the play store (SlimSocial for Facebook).

All the advanced webview code is in the [main class](https://github.com/rignaneseleo/SlimSocial-for-Facebook/blob/master/SlimFacebook/app/src/main/java/it/rignanese/leo/slimfacebook/MainActivity.java) (if you want to see)

**Comment by sazid** [comment]
Try this:

```
@Override
public void onResume() {
    super.onResume();
    yourWebView.onResume();
    if (yourWebView.canGoBack() && yourWebView.getUrl() is an external url) {
        yourWebView.goBack();
    }
}
```

**Comment by ocram** [comment]
@rignaneseleo Looking at your description, it really appears that your `WebView` navigates to a new page just before the external URL is opened (and handled externaly).

Thus @sazid's solution may indeed be a working (albeit a little dirty) workaround :)

Apart from that, can you please check the values of the following methods *after* the screen has become blank? They might give us some hints as to what is actually happening in the `WebView`.

 * `WebView#getUrl`
 * `WebView#getOriginalUrl`
 * `WebView#getTitle`
 * `WebView#getProgress`

By the way, can you re-produce the problem when using Android's simple built-in `WebView` and handling external URLs in `shouldOverrideUrlLoading`?

**Comment by rignaneseleo** [comment]
I've seen that the white page there is only if I change the user agent:
`settings.setUserAgentString("Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.1.0.4633 Mobile Safari/537.10+");`

There are other apps that use this user agent without problems. Where is the issue?

**Comment by ocram** [comment]
> I've seen that the white page there is only with this user agent

Oh, that's strange. But great that you found out. Thank you!

> Where is the issue?

No idea, sorry. That's some random user agent that I've never seen before, and every site may react to it in another way.

> There are other apps that use this user agent without problems

Really? Which? Why is this particular user agent popular?

Are you sure that it's just this one user agent? What happens if you change it to something similar? Can you find one that works but which provides the same benefits?

Why do you need the user agent to change at all, by the way? Can't you just keep the default value for mobile view and call

```java
mWebView.setDesktopMode(true);
```

for desktop view, in case you need it?

**Comment by rignaneseleo** [comment]
I've removed the custom user agent and set
`mWebView.setDesktopMode(true);`

It seems work well 👍 

Thanks!
