### ISSUE TITLE
Add title bar and loading indicator

### ISSUE THREAD

**Issue by digitalprecision** [delight-im/Android-AdvancedWebView#87]
What would be the best way to add a title bar ~50pix (very top), and loading indicator ~10px (under title bar) at the top of the webview? The title bar will never disappear, and the loading indicator would only appear when pages are loading.

**Comment by ocram** [comment]
Thanks for your question!

Regarding loading indicators, I've just found this old issue: https://github.com/delight-im/Android-AdvancedWebView/issues/34 I've added some more information there, so let's keep the discussion in that other thread.

Turning to the title bar, could you show some screenshot or drawing of something that resembles what you want?

**Comment by ocram** [comment]
In general, https://github.com/delight-im/Android-AdvancedWebView/issues/88 could be what you want as well.

**Comment by digitalprecision** [comment]
Awesome thanks!

**Comment by digitalprecision** [comment]
Here is a screen of my iphone webview, notice the gray bar at the top with the page title.
![img_0817](https://cloud.githubusercontent.com/assets/234718/19460218/72d3af9a-948e-11e6-9f75-32734402e3ba.PNG)
