### ISSUE TITLE
Cookies not working

### ISSUE THREAD

**Issue by digitalprecision** [delight-im/Android-AdvancedWebView#92]
According to the docs, it appears that cookies are enabled by default, but when I go through the app (using Advanced WebView) the cookie I set to redirect user back to their last viewed page after logging it, it doesn't work, but it does work in Chrome on the same device.

Do we have to manually call sync(), or something else to ensure cookies can be stored on the device?

**Comment by digitalprecision** [comment]
Closing this issue, it was issue with my code on server side, not your code. I had no idea that android devices do not persist the HTTP_REFERER value.

**Comment by ocram** [comment]
Thanks for your question and for solving the problem!

I can't find anything in Android's documentation that suggests that the `Referer` header is not being sent inside `WebView` instances.

In general, you can check which request headers are being sent from your `WebView` instance by writing them all to the output on the server:
http://httpbin.org/
http://httpbin.org/headers

Using the method `AdvancedWebView#addHttpHeader` you can add your own headers, but it may indeed be a better idea to adjust the server-side code.

**Comment by digitalprecision** [comment]
I was able to check the headers by dumping them to the error log of my dev site, that's when I noticed that HTTP_REFERER was not in the headers for the native app, but was in the headers for the request via Chrome. I simply adjusted server side code to set redirect.

Thanks!
