### ISSUE TITLE
night mode option

### ISSUE THREAD

**Issue by deepti1408** [delight-im/Android-AdvancedWebView#97]
Hi , thank you for this wonderful library. I was looking for option to invert colors as in night mode. is this possible through this lib?

**Comment by ocram** [comment]
Thanks for your appreciation and the feature request!

Night mode (or inverting colors) has not been built into this library, yet. If there is demand for this feature (which has not been the case so far), we might add it.

In the meantime, you might wrap some layout container around your `AdvancedWebView` instance (in the XML layout) and then apply some color filter to that parent layout that inverts the colors (in Java code). This has not been tested, but it *might* work.

Another idea would be to execute some JavaScript after a page has loaded, which could invert the colors using a CSS property such as `filter` set to `invert(100%)`. Don't know if that really works on all page content, though. Might be worth an attempt. You could even test this by temporarily adding it to your static CSS.

Would love to hear about the results if you try. Hope that helps!

**Comment by ocram** [comment]
We won’t implement anything like this for now.
